INSERT INTO sjbrett_AdvAcct.NL_ACCOUNTS
(
  NCODE
 ,NNAME
 ,NCURRENCYCODE
 ,NTYPE
 ,NOPENBALMONTH
 ,NOPENBALYEAR
 ,NOPENBALMTH_C
 ,NOPENBALYR_C
 ,NBALANCE
 ,NTURNOVERPTD
 ,NTURNOVERYTD
 ,NTURNOVERLY
 ,NBALANCE_C
 ,NTURNOVRPTD_C
 ,NTURNOVRYTD_C
 ,NTURNOVRLY_C
 ,NBUDGETPTD
 ,NBUDGETYTD
 ,NBUDGETLY
 ,NBUDGETPTD_C
 ,NBUDGETYTD_C
 ,NBUDGETLY_C
 ,`NCATE;RYCODE5`
 ,`NCATE;RYCODE6`
 ,`NCATE;RYCODE7`
 ,`NCATE;RYCODE8`
 ,NNOTES
 ,N_EXCLUDE_TRNREP
 ,N_COUNTRY_CODE
 ,NYEAR_END_CODE
 ,NUSED
 ,N_PROFILE_REC
 ,N_PROFILE_NL
 ,N_PROFILE_SL
 ,N_PROFILE_PL
 ,N_PROFILE_WARN
 ,N_RECON_COUNTER
 ,NRECONBALANCE
 ,NRECONBALANCE_C
 ,N_INCOME
 ,N_INCOME_C
 ,N_EXPENSES
 ,N_EXPENSES_C
 ,NOPENBALANCELY
 ,NOPENBALANCLY_C
 ,NTURNOVER_L1
 ,NTURNOVER_L2
 ,NTURNOVER_L3
 ,NTURNOVER_L4
 ,NTURNOVER_L5
 ,NTURNOVER_L6
 ,NTURNOVER_L7
 ,NTURNOVER_L8
 ,NTURNOVER_L9
 ,NTURNOVER_L10
 ,NTURNOVER_L11
 ,NTURNOVER_L12
 ,NTURNOVER_L13
 ,NTURNOVER_C1
 ,NTURNOVER_C2
 ,NTURNOVER_C3
 ,NTURNOVER_C4
 ,NTURNOVER_C5
 ,NTURNOVER_C6
 ,NTURNOVER_C7
 ,NTURNOVER_C8
 ,NTURNOVER_C9
 ,NTURNOVER_C10
 ,NTURNOVER_C11
 ,NTURNOVER_C12
 ,NTURNOVER_C13
 ,NTURNOVER_N1
 ,NTURNOVER_N2
 ,NTURNOVER_N3
 ,NTURNOVER_N4
 ,NTURNOVER_N5
 ,NTURNOVER_N6
 ,NTURNOVER_N7
 ,NTURNOVER_N8
 ,NTURNOVER_N9
 ,NTURNOVER_N10
 ,NTURNOVER_N11
 ,NTURNOVER_N12
 ,NTURNOVER_N13
 ,NTURNOVER_L1_C
 ,NTURNOVER_L2_C
 ,NTURNOVER_L3_C
 ,NTURNOVER_L4_C
 ,NTURNOVER_L5_C
 ,NTURNOVER_L6_C
 ,NTURNOVER_L7_C
 ,NTURNOVER_L8_C
 ,NTURNOVER_L9_C
 ,NTURNOVER_L10_C
 ,NTURNOVER_L11_C
 ,NTURNOVER_L12_C
 ,NTURNOVER_L13_C
 ,NTURNOVER_C1_C
 ,NTURNOVER_C2_C
 ,NTURNOVER_C3_C
 ,NTURNOVER_C4_C
 ,NTURNOVER_C5_C
 ,NTURNOVER_C6_C
 ,NTURNOVER_C7_C
 ,NTURNOVER_C8_C
 ,NTURNOVER_C9_C
 ,NTURNOVER_C10_C
 ,NTURNOVER_C11_C
 ,NTURNOVER_C12_C
 ,NTURNOVER_C13_C
 ,NTURNOVER_N1_C
 ,NTURNOVER_N2_C
 ,NTURNOVER_N3_C
 ,NTURNOVER_N4_C
 ,NTURNOVER_N5_C
 ,NTURNOVER_N6_C
 ,NTURNOVER_N7_C
 ,NTURNOVER_N8_C
 ,NTURNOVER_N9_C
 ,NTURNOVER_N10_C
 ,NTURNOVER_N11_C
 ,NTURNOVER_N12_C
 ,NTURNOVER_N13_C
 ,NBUDGET_L1
 ,NBUDGET_L2
 ,NBUDGET_L3
 ,NBUDGET_L4
 ,NBUDGET_L5
 ,NBUDGET_L6
 ,NBUDGET_L7
 ,NBUDGET_L8
 ,NBUDGET_L9
 ,NBUDGET_L10
 ,NBUDGET_L11
 ,NBUDGET_L12
 ,NBUDGET_L13
 ,NBUDGET_C1
 ,NBUDGET_C2
 ,NBUDGET_C3
 ,NBUDGET_C4
 ,NBUDGET_C5
 ,NBUDGET_C6
 ,NBUDGET_C7
 ,NBUDGET_C8
 ,NBUDGET_C9
 ,NBUDGET_C10
 ,NBUDGET_C11
 ,NBUDGET_C12
 ,NBUDGET_C13
 ,NBUDGET_N1
 ,NBUDGET_N2
 ,NBUDGET_N3
 ,NBUDGET_N4
 ,NBUDGET_N5
 ,NBUDGET_N6
 ,NBUDGET_N7
 ,NBUDGET_N8
 ,NBUDGET_N9
 ,NBUDGET_N10
 ,NBUDGET_N11
 ,NBUDGET_N12
 ,NBUDGET_N13
 ,NBUDGET_L1_O
 ,NBUDGET_L2_O
 ,NBUDGET_L3_O
 ,NBUDGET_L4_O
 ,NBUDGET_L5_O
 ,NBUDGET_L6_O
 ,NBUDGET_L7_O
 ,NBUDGET_L8_O
 ,NBUDGET_L9_O
 ,NBUDGET_L10_O
 ,NBUDGET_L11_O
 ,NBUDGET_L12_O
 ,NBUDGET_L13_O
 ,NBUDGET_C1_O
 ,NBUDGET_C2_O
 ,NBUDGET_C3_O
 ,NBUDGET_C4_O
 ,NBUDGET_C5_O
 ,NBUDGET_C6_O
 ,NBUDGET_C7_O
 ,NBUDGET_C8_O
 ,NBUDGET_C9_O
 ,NBUDGET_C10_O
 ,NBUDGET_C11_O
 ,NBUDGET_C12_O
 ,NBUDGET_C13_O
 ,NBUDGET_N1_O
 ,NBUDGET_N2_O
 ,NBUDGET_N3_O
 ,NBUDGET_N4_O
 ,NBUDGET_N5_O
 ,NBUDGET_N6_O
 ,NBUDGET_N7_O
 ,NBUDGET_N8_O
 ,NBUDGET_N9_O
 ,NBUDGET_N10_O
 ,NBUDGET_N11_O
 ,NBUDGET_N12_O
 ,NBUDGET_N13_O
 ,N_USER_EDITED
 ,N_USER_PUTIN
 ,N_DATE_PUTIN
 ,N_DATE_EDITED
 ,N_MU_STATUS
 ,`NCATE;RYCODE4`
 ,NCOPY_ACCCODE
 ,`NCATE;RYCODE1`
 ,`NCATE;RYCODE2`
 ,`NCATE;RYCODE3`
 ,NMAJORHEADCODE
 ,N_PRIMARY
 ,N_LAST_STATEMENT
 ,N_EXCLUDE_RECREP
 ,N_CENTRALISED
 ,N_VATNONDEDUCT
 ,N_VATCODE
 ,N_FORCE_COSTING
 ,N_SOURCE
 ,N_USE_ZERO_BUDGET
 ,N_OVERDRAFT
 ,N_DO_NOT_USE
 ,N_EMISSIONS_GROUP_LINK
 ,N_CLASSIFICATION_LINK
 ,N_ACCOUNT_FOR_CO2
 ,N_DEFAULT_COSTCENTRE
 ,NREPORTING_CODE
)
VALUES
(
  '' -- NCODE - VARCHAR(25)
 ,'' -- NNAME - VARCHAR(40)
 ,'' -- NCURRENCYCODE - VARCHAR(4)
 ,'' -- NTYPE - VARCHAR(1)
 ,0 -- NOPENBALMONTH - DOUBLE
 ,0 -- NOPENBALYEAR - DOUBLE
 ,0 -- NOPENBALMTH_C - DOUBLE
 ,0 -- NOPENBALYR_C - DOUBLE
 ,0 -- NBALANCE - DOUBLE
 ,0 -- NTURNOVERPTD - DOUBLE
 ,0 -- NTURNOVERYTD - DOUBLE
 ,0 -- NTURNOVERLY - DOUBLE
 ,0 -- NBALANCE_C - DOUBLE
 ,0 -- NTURNOVRPTD_C - DOUBLE
 ,0 -- NTURNOVRYTD_C - DOUBLE
 ,0 -- NTURNOVRLY_C - DOUBLE
 ,0 -- NBUDGETPTD - DOUBLE
 ,0 -- NBUDGETYTD - DOUBLE
 ,0 -- NBUDGETLY - DOUBLE
 ,0 -- NBUDGETPTD_C - DOUBLE
 ,0 -- NBUDGETYTD_C - DOUBLE
 ,0 -- NBUDGETLY_C - DOUBLE
 ,'' -- NCATE;RYCODE5 - VARCHAR(6)
 ,'' -- NCATE;RYCODE6 - VARCHAR(6)
 ,'' -- NCATE;RYCODE7 - VARCHAR(6)
 ,'' -- NCATE;RYCODE8 - VARCHAR(6)
 ,'' -- NNOTES - TEXT
 ,0 -- N_EXCLUDE_TRNREP - TINYINT(4)
 ,'' -- N_COUNTRY_CODE - VARCHAR(4)
 ,'' -- NYEAR_END_CODE - VARCHAR(25)
 ,0 -- NUSED - TINYINT(4)
 ,0 -- N_PROFILE_REC - TINYINT(4)
 ,0 -- N_PROFILE_NL - TINYINT(4)
 ,0 -- N_PROFILE_SL - TINYINT(4)
 ,0 -- N_PROFILE_PL - TINYINT(4)
 ,0 -- N_PROFILE_WARN - TINYINT(4)
 ,0 -- N_RECON_COUNTER - DOUBLE
 ,0 -- NRECONBALANCE - DOUBLE
 ,0 -- NRECONBALANCE_C - DOUBLE
 ,0 -- N_INCOME - DOUBLE
 ,0 -- N_INCOME_C - DOUBLE
 ,0 -- N_EXPENSES - DOUBLE
 ,0 -- N_EXPENSES_C - DOUBLE
 ,0 -- NOPENBALANCELY - DOUBLE
 ,0 -- NOPENBALANCLY_C - DOUBLE
 ,0 -- NTURNOVER_L1 - DOUBLE
 ,0 -- NTURNOVER_L2 - DOUBLE
 ,0 -- NTURNOVER_L3 - DOUBLE
 ,0 -- NTURNOVER_L4 - DOUBLE
 ,0 -- NTURNOVER_L5 - DOUBLE
 ,0 -- NTURNOVER_L6 - DOUBLE
 ,0 -- NTURNOVER_L7 - DOUBLE
 ,0 -- NTURNOVER_L8 - DOUBLE
 ,0 -- NTURNOVER_L9 - DOUBLE
 ,0 -- NTURNOVER_L10 - DOUBLE
 ,0 -- NTURNOVER_L11 - DOUBLE
 ,0 -- NTURNOVER_L12 - DOUBLE
 ,0 -- NTURNOVER_L13 - DOUBLE
 ,0 -- NTURNOVER_C1 - DOUBLE
 ,0 -- NTURNOVER_C2 - DOUBLE
 ,0 -- NTURNOVER_C3 - DOUBLE
 ,0 -- NTURNOVER_C4 - DOUBLE
 ,0 -- NTURNOVER_C5 - DOUBLE
 ,0 -- NTURNOVER_C6 - DOUBLE
 ,0 -- NTURNOVER_C7 - DOUBLE
 ,0 -- NTURNOVER_C8 - DOUBLE
 ,0 -- NTURNOVER_C9 - DOUBLE
 ,0 -- NTURNOVER_C10 - DOUBLE
 ,0 -- NTURNOVER_C11 - DOUBLE
 ,0 -- NTURNOVER_C12 - DOUBLE
 ,0 -- NTURNOVER_C13 - DOUBLE
 ,0 -- NTURNOVER_N1 - DOUBLE
 ,0 -- NTURNOVER_N2 - DOUBLE
 ,0 -- NTURNOVER_N3 - DOUBLE
 ,0 -- NTURNOVER_N4 - DOUBLE
 ,0 -- NTURNOVER_N5 - DOUBLE
 ,0 -- NTURNOVER_N6 - DOUBLE
 ,0 -- NTURNOVER_N7 - DOUBLE
 ,0 -- NTURNOVER_N8 - DOUBLE
 ,0 -- NTURNOVER_N9 - DOUBLE
 ,0 -- NTURNOVER_N10 - DOUBLE
 ,0 -- NTURNOVER_N11 - DOUBLE
 ,0 -- NTURNOVER_N12 - DOUBLE
 ,0 -- NTURNOVER_N13 - DOUBLE
 ,0 -- NTURNOVER_L1_C - DOUBLE
 ,0 -- NTURNOVER_L2_C - DOUBLE
 ,0 -- NTURNOVER_L3_C - DOUBLE
 ,0 -- NTURNOVER_L4_C - DOUBLE
 ,0 -- NTURNOVER_L5_C - DOUBLE
 ,0 -- NTURNOVER_L6_C - DOUBLE
 ,0 -- NTURNOVER_L7_C - DOUBLE
 ,0 -- NTURNOVER_L8_C - DOUBLE
 ,0 -- NTURNOVER_L9_C - DOUBLE
 ,0 -- NTURNOVER_L10_C - DOUBLE
 ,0 -- NTURNOVER_L11_C - DOUBLE
 ,0 -- NTURNOVER_L12_C - DOUBLE
 ,0 -- NTURNOVER_L13_C - DOUBLE
 ,0 -- NTURNOVER_C1_C - DOUBLE
 ,0 -- NTURNOVER_C2_C - DOUBLE
 ,0 -- NTURNOVER_C3_C - DOUBLE
 ,0 -- NTURNOVER_C4_C - DOUBLE
 ,0 -- NTURNOVER_C5_C - DOUBLE
 ,0 -- NTURNOVER_C6_C - DOUBLE
 ,0 -- NTURNOVER_C7_C - DOUBLE
 ,0 -- NTURNOVER_C8_C - DOUBLE
 ,0 -- NTURNOVER_C9_C - DOUBLE
 ,0 -- NTURNOVER_C10_C - DOUBLE
 ,0 -- NTURNOVER_C11_C - DOUBLE
 ,0 -- NTURNOVER_C12_C - DOUBLE
 ,0 -- NTURNOVER_C13_C - DOUBLE
 ,0 -- NTURNOVER_N1_C - DOUBLE
 ,0 -- NTURNOVER_N2_C - DOUBLE
 ,0 -- NTURNOVER_N3_C - DOUBLE
 ,0 -- NTURNOVER_N4_C - DOUBLE
 ,0 -- NTURNOVER_N5_C - DOUBLE
 ,0 -- NTURNOVER_N6_C - DOUBLE
 ,0 -- NTURNOVER_N7_C - DOUBLE
 ,0 -- NTURNOVER_N8_C - DOUBLE
 ,0 -- NTURNOVER_N9_C - DOUBLE
 ,0 -- NTURNOVER_N10_C - DOUBLE
 ,0 -- NTURNOVER_N11_C - DOUBLE
 ,0 -- NTURNOVER_N12_C - DOUBLE
 ,0 -- NTURNOVER_N13_C - DOUBLE
 ,0 -- NBUDGET_L1 - DOUBLE
 ,0 -- NBUDGET_L2 - DOUBLE
 ,0 -- NBUDGET_L3 - DOUBLE
 ,0 -- NBUDGET_L4 - DOUBLE
 ,0 -- NBUDGET_L5 - DOUBLE
 ,0 -- NBUDGET_L6 - DOUBLE
 ,0 -- NBUDGET_L7 - DOUBLE
 ,0 -- NBUDGET_L8 - DOUBLE
 ,0 -- NBUDGET_L9 - DOUBLE
 ,0 -- NBUDGET_L10 - DOUBLE
 ,0 -- NBUDGET_L11 - DOUBLE
 ,0 -- NBUDGET_L12 - DOUBLE
 ,0 -- NBUDGET_L13 - DOUBLE
 ,0 -- NBUDGET_C1 - DOUBLE
 ,0 -- NBUDGET_C2 - DOUBLE
 ,0 -- NBUDGET_C3 - DOUBLE
 ,0 -- NBUDGET_C4 - DOUBLE
 ,0 -- NBUDGET_C5 - DOUBLE
 ,0 -- NBUDGET_C6 - DOUBLE
 ,0 -- NBUDGET_C7 - DOUBLE
 ,0 -- NBUDGET_C8 - DOUBLE
 ,0 -- NBUDGET_C9 - DOUBLE
 ,0 -- NBUDGET_C10 - DOUBLE
 ,0 -- NBUDGET_C11 - DOUBLE
 ,0 -- NBUDGET_C12 - DOUBLE
 ,0 -- NBUDGET_C13 - DOUBLE
 ,0 -- NBUDGET_N1 - DOUBLE
 ,0 -- NBUDGET_N2 - DOUBLE
 ,0 -- NBUDGET_N3 - DOUBLE
 ,0 -- NBUDGET_N4 - DOUBLE
 ,0 -- NBUDGET_N5 - DOUBLE
 ,0 -- NBUDGET_N6 - DOUBLE
 ,0 -- NBUDGET_N7 - DOUBLE
 ,0 -- NBUDGET_N8 - DOUBLE
 ,0 -- NBUDGET_N9 - DOUBLE
 ,0 -- NBUDGET_N10 - DOUBLE
 ,0 -- NBUDGET_N11 - DOUBLE
 ,0 -- NBUDGET_N12 - DOUBLE
 ,0 -- NBUDGET_N13 - DOUBLE
 ,0 -- NBUDGET_L1_O - DOUBLE
 ,0 -- NBUDGET_L2_O - DOUBLE
 ,0 -- NBUDGET_L3_O - DOUBLE
 ,0 -- NBUDGET_L4_O - DOUBLE
 ,0 -- NBUDGET_L5_O - DOUBLE
 ,0 -- NBUDGET_L6_O - DOUBLE
 ,0 -- NBUDGET_L7_O - DOUBLE
 ,0 -- NBUDGET_L8_O - DOUBLE
 ,0 -- NBUDGET_L9_O - DOUBLE
 ,0 -- NBUDGET_L10_O - DOUBLE
 ,0 -- NBUDGET_L11_O - DOUBLE
 ,0 -- NBUDGET_L12_O - DOUBLE
 ,0 -- NBUDGET_L13_O - DOUBLE
 ,0 -- NBUDGET_C1_O - DOUBLE
 ,0 -- NBUDGET_C2_O - DOUBLE
 ,0 -- NBUDGET_C3_O - DOUBLE
 ,0 -- NBUDGET_C4_O - DOUBLE
 ,0 -- NBUDGET_C5_O - DOUBLE
 ,0 -- NBUDGET_C6_O - DOUBLE
 ,0 -- NBUDGET_C7_O - DOUBLE
 ,0 -- NBUDGET_C8_O - DOUBLE
 ,0 -- NBUDGET_C9_O - DOUBLE
 ,0 -- NBUDGET_C10_O - DOUBLE
 ,0 -- NBUDGET_C11_O - DOUBLE
 ,0 -- NBUDGET_C12_O - DOUBLE
 ,0 -- NBUDGET_C13_O - DOUBLE
 ,0 -- NBUDGET_N1_O - DOUBLE
 ,0 -- NBUDGET_N2_O - DOUBLE
 ,0 -- NBUDGET_N3_O - DOUBLE
 ,0 -- NBUDGET_N4_O - DOUBLE
 ,0 -- NBUDGET_N5_O - DOUBLE
 ,0 -- NBUDGET_N6_O - DOUBLE
 ,0 -- NBUDGET_N7_O - DOUBLE
 ,0 -- NBUDGET_N8_O - DOUBLE
 ,0 -- NBUDGET_N9_O - DOUBLE
 ,0 -- NBUDGET_N10_O - DOUBLE
 ,0 -- NBUDGET_N11_O - DOUBLE
 ,0 -- NBUDGET_N12_O - DOUBLE
 ,0 -- NBUDGET_N13_O - DOUBLE
 ,'' -- N_USER_EDITED - VARCHAR(4)
 ,'' -- N_USER_PUTIN - VARCHAR(4)
 ,NOW() -- N_DATE_PUTIN - DATETIME
 ,NOW() -- N_DATE_EDITED - DATETIME
 ,'' -- N_MU_STATUS - VARCHAR(1)
 ,'' -- NCATE;RYCODE4 - VARCHAR(6)
 ,'' -- NCOPY_ACCCODE - VARCHAR(25)
 ,'' -- NCATE;RYCODE1 - VARCHAR(6)
 ,'' -- NCATE;RYCODE2 - VARCHAR(6)
 ,'' -- NCATE;RYCODE3 - VARCHAR(6)
 ,0 -- NMAJORHEADCODE - TINYINT(4)
 ,0 -- N_PRIMARY - DOUBLE NOT NULL
 ,0 -- N_LAST_STATEMENT - DOUBLE
 ,0 -- N_EXCLUDE_RECREP - TINYINT(4)
 ,0 -- N_CENTRALISED - TINYINT(4)
 ,0 -- N_VATNONDEDUCT - DOUBLE
 ,'' -- N_VATCODE - VARCHAR(4)
 ,0 -- N_FORCE_COSTING - TINYINT(4)
 ,'' -- N_SOURCE - VARCHAR(1)
 ,0 -- N_USE_ZERO_BUDGET - TINYINT(4)
 ,0 -- N_OVERDRAFT - DOUBLE NOT NULL
 ,0 -- N_DO_NOT_USE - TINYINT(4) NOT NULL
 ,0 -- N_EMISSIONS_GROUP_LINK - INT(11)
 ,0 -- N_CLASSIFICATION_LINK - INT(11)
 ,0 -- N_ACCOUNT_FOR_CO2 - TINYINT(4) NOT NULL
 ,'' -- N_DEFAULT_COSTCENTRE - VARCHAR(10) NOT NULL
 ,0 -- NREPORTING_CODE - INT(11) NOT NULL
)