INSERT INTO sjbrett_AdvAcct.NL_CATEGORIES
(
  NCAT_PRIMARY
 ,NCAT_CODE
 ,NCAT_NAME
 ,NCAT_SHORTNAME
 ,NCAT_NUMBER
 ,NCAT_USED
 ,NCAT_DRCR_TYPE
 ,NCAT_MAJOR_HEADING
 ,NCAT_TAXCODE_DR
 ,NCAT_TAXCODE_CR
 ,NCAT_LEVEL
 ,NCAT_CURR_SYMBOL
 ,NCAT_BANK_ACCOUNT
 ,NCAT_PETTY_CASH_ACCOUNT
 ,NCAT_COMPULSORY_COSTING
 ,NCAT_ACCOUNT_FOR_CO2
 ,NCAT_EMISSIONS_GROUP_LINK
 ,NCAT_CLASSIFICATION_LINK
 ,NCAT_INACTIVE
 ,NCAT_SORT
 ,NCAT_REPORTING_CODE
)
VALUES
(
  0 -- NCAT_PRIMARY - INT(11) NOT NULL
 ,'' -- NCAT_CODE - VARCHAR(6) NOT NULL
 ,'' -- NCAT_NAME - VARCHAR(50)
 ,'' -- NCAT_SHORTNAME - VARCHAR(10)
 ,0 -- NCAT_NUMBER - TINYINT(4) NOT NULL
 ,0 -- NCAT_USED - TINYINT(4) NOT NULL
 ,0 -- NCAT_DRCR_TYPE - TINYINT(4)
 ,0 -- NCAT_MAJOR_HEADING - TINYINT(4)
 ,'' -- NCAT_TAXCODE_DR - VARCHAR(4)
 ,'' -- NCAT_TAXCODE_CR - VARCHAR(4)
 ,0 -- NCAT_LEVEL - INT(11)
 ,'' -- NCAT_CURR_SYMBOL - VARCHAR(4)
 ,0 -- NCAT_BANK_ACCOUNT - TINYINT(4) NOT NULL
 ,0 -- NCAT_PETTY_CASH_ACCOUNT - TINYINT(4) NOT NULL
 ,0 -- NCAT_COMPULSORY_COSTING - TINYINT(4) NOT NULL
 ,0 -- NCAT_ACCOUNT_FOR_CO2 - TINYINT(4) NOT NULL
 ,0 -- NCAT_EMISSIONS_GROUP_LINK - INT(11)
 ,0 -- NCAT_CLASSIFICATION_LINK - INT(11)
 ,0 -- NCAT_INACTIVE - TINYINT(4) NOT NULL
 ,'' -- NCAT_SORT - VARCHAR(20)
 ,0 -- NCAT_REPORTING_CODE - INT(11)
)