INSERT INTO sjbrett_AdvAcct.PL_ADDRESSES
(
  PL_AD_ACCCODE
 ,PL_AD_CODE
 ,PL_AD_CON_CODE
 ,PL_AD_ADDRESS
 ,PL_AD_POSTCODE
 ,PL_AD_ADDRESS_USER1
 ,PL_AD_ADDRESS_USER2
 ,PL_AD_PHONE
 ,PL_AD_FAX
 ,PL_AD_CONTACT
 ,PL_AD_CONT_SAL
 ,PL_AD_INV_ADD
 ,PL_AD_DEL_ADD
 ,PL_AD_STAT_ADD
 ,PL_AD_REM_ADD
 ,PL_AD_NOTE
 ,PL_AD_CON_TITLE
 ,PL_AD_CON_INITS
 ,PL_AD_CON_SNAME
 ,PL_AD_CON_JOB
 ,PL_AD_USRCHAR1
 ,PL_AD_USRCHAR2
 ,PL_AD_USRCHAR3
 ,PL_AD_USRCHAR4
 ,PL_AD_USRCHAR5
 ,PL_AD_USRCHAR6
 ,PL_AD_USRCHAR7
 ,PL_AD_USRCHAR8
 ,PL_AD_USRFLAG1
 ,PL_AD_USRFLAG2
 ,PL_AD_USRFLAG3
 ,PL_AD_USRDATE1
 ,PL_AD_USRDATE2
 ,PL_AD_USRDATE3
 ,PL_AD_USRNUM1
 ,PL_AD_USRNUM2
 ,PL_AD_USRNUM3
 ,PL_AD_ANA_NUMBER
 ,PL_AD_PRIMARY
 ,PL_AD_ANALYSIS
 ,PL_AD_DEL_ADDRESS_2
 ,PL_AD_SOURCE
 ,PL_AD_EMAIL
 ,PL_AD_CC_EMAIL
 ,PL_AD_COUNTRY
 ,PL_AD_CON_FNAME
 ,PL_AD_DO_NOT_USE
 ,PL_AD_MOBILE
 ,PL_AD_USER_EDITED
 ,PL_AD_USER_PUTIN
 ,PL_AD_DATE_PUTIN
 ,PL_AD_DATE_EDITED
)
VALUES
(
  '' -- PL_AD_ACCCODE - VARCHAR(10)
 ,0 -- PL_AD_CODE - DOUBLE
 ,'' -- PL_AD_CON_CODE - VARCHAR(16)
 ,'' -- PL_AD_ADDRESS - VARCHAR(160)
 ,'' -- PL_AD_POSTCODE - VARCHAR(12)
 ,'' -- PL_AD_ADDRESS_USER1 - VARCHAR(30)
 ,'' -- PL_AD_ADDRESS_USER2 - VARCHAR(30)
 ,'' -- PL_AD_PHONE - VARCHAR(20)
 ,'' -- PL_AD_FAX - VARCHAR(20)
 ,'' -- PL_AD_CONTACT - VARCHAR(30)
 ,'' -- PL_AD_CONT_SAL - VARCHAR(20)
 ,0 -- PL_AD_INV_ADD - TINYINT(4)
 ,0 -- PL_AD_DEL_ADD - TINYINT(4)
 ,0 -- PL_AD_STAT_ADD - TINYINT(4)
 ,0 -- PL_AD_REM_ADD - TINYINT(4)
 ,'' -- PL_AD_NOTE - VARCHAR(240)
 ,'' -- PL_AD_CON_TITLE - VARCHAR(5)
 ,'' -- PL_AD_CON_INITS - VARCHAR(15)
 ,'' -- PL_AD_CON_SNAME - VARCHAR(30)
 ,'' -- PL_AD_CON_JOB - VARCHAR(35)
 ,'' -- PL_AD_USRCHAR1 - VARCHAR(20)
 ,'' -- PL_AD_USRCHAR2 - VARCHAR(20)
 ,'' -- PL_AD_USRCHAR3 - VARCHAR(100)
 ,'' -- PL_AD_USRCHAR4 - VARCHAR(100)
 ,'' -- PL_AD_USRCHAR5 - VARCHAR(20)
 ,'' -- PL_AD_USRCHAR6 - VARCHAR(30)
 ,'' -- PL_AD_USRCHAR7 - VARCHAR(30)
 ,'' -- PL_AD_USRCHAR8 - VARCHAR(30)
 ,0 -- PL_AD_USRFLAG1 - TINYINT(4)
 ,0 -- PL_AD_USRFLAG2 - TINYINT(4)
 ,0 -- PL_AD_USRFLAG3 - TINYINT(4)
 ,NOW() -- PL_AD_USRDATE1 - DATETIME
 ,NOW() -- PL_AD_USRDATE2 - DATETIME
 ,NOW() -- PL_AD_USRDATE3 - DATETIME
 ,0 -- PL_AD_USRNUM1 - DOUBLE
 ,0 -- PL_AD_USRNUM2 - DOUBLE
 ,0 -- PL_AD_USRNUM3 - DOUBLE
 ,'' -- PL_AD_ANA_NUMBER - VARCHAR(13)
 ,0 -- PL_AD_PRIMARY - DOUBLE NOT NULL
 ,'' -- PL_AD_ANALYSIS - VARCHAR(25)
 ,0 -- PL_AD_DEL_ADDRESS_2 - TINYINT(4)
 ,'' -- PL_AD_SOURCE - VARCHAR(1)
 ,'' -- PL_AD_EMAIL - VARCHAR(64)
 ,'' -- PL_AD_CC_EMAIL - VARCHAR(64)
 ,'' -- PL_AD_COUNTRY - VARCHAR(35)
 ,'' -- PL_AD_CON_FNAME - VARCHAR(20)
 ,0 -- PL_AD_DO_NOT_USE - TINYINT(4)
 ,'' -- PL_AD_MOBILE - VARCHAR(20)
 ,'' -- PL_AD_USER_EDITED - VARCHAR(4)
 ,'' -- PL_AD_USER_PUTIN - VARCHAR(4)
 ,NOW() -- PL_AD_DATE_PUTIN - DATETIME
 ,NOW() -- PL_AD_DATE_EDITED - DATETIME
)