INSERT INTO sjbrett_AdvAcct.PL_ACCOUNTS
(
  SUCODE
 ,SUNAME
 ,SUADDRESS
 ,SUPOSTCODE
 ,SUPHONE
 ,SUPHONE2
 ,SUFAX
 ,SUCONTACT
 ,SUSALUTE
 ,SU_MULTI_CURR
 ,SU_IMPORT_CODE
 ,SU_COUNTRY_CODE
 ,SU_VAT_REG_NO
 ,SU_EC_DELIVERY
 ,SU_EC_T_NATURE
 ,SU_EC_T_MODE
 ,SUBALANCE
 ,SUBALANCE_C
 ,SUAGED_1
 ,SUAGED_2
 ,SUAGED_3
 ,SUAGED_4
 ,SUAGED_UNALLOC
 ,SUSORT
 ,SUUSER1
 ,SUUSER2
 ,SUUSER3
 ,SUUSED
 ,SU_US1099
 ,SUTURNOVERPTD
 ,SUTURNOVR_L1
 ,SUTURNOVR_L2
 ,SUTURNOVR_L3
 ,SUTURNOVR_L4
 ,SUTURNOVR_L5
 ,SUTURNOVR_L6
 ,SUTURNOVR_L7
 ,SUTURNOVR_L8
 ,SUTURNOVR_L9
 ,SUTURNOVR_L10
 ,SUTURNOVR_L11
 ,SUTURNOVR_L12
 ,SUTURNOVR_L13
 ,SUTURNOVR_C1
 ,SUTURNOVR_C2
 ,SUTURNOVR_C3
 ,SUTURNOVR_C4
 ,SUTURNOVR_C5
 ,SUTURNOVR_C6
 ,SUTURNOVR_C7
 ,SUTURNOVR_C8
 ,SUTURNOVR_C9
 ,SUTURNOVR_C10
 ,SUTURNOVR_C11
 ,SUTURNOVR_C12
 ,SUTURNOVR_C13
 ,SUTURNOVR_O1
 ,SUTURNOVR_O2
 ,SUTURNOVR_O3
 ,SUTURNOVR_O4
 ,SUTURNOVR_O5
 ,SUTURNOVR_O6
 ,SUTURNOVR_O7
 ,SUTURNOVR_O8
 ,SUTURNOVR_O9
 ,SUTURNOVR_O10
 ,SUTURNOVR_O11
 ,SUTURNOVR_O12
 ,SUTURNOVR_O13
 ,SUTURNOVERYTD
 ,SUCURRENCYCODE
 ,SUTURNOVR_L1_C
 ,SUTURNOVR_L2_C
 ,SUTURNOVR_L3_C
 ,SUTURNOVR_L4_C
 ,SUTURNOVR_L5_C
 ,SUTURNOVR_L6_C
 ,SUTURNOVR_L7_C
 ,SUTURNOVR_L8_C
 ,SUTURNOVR_L9_C
 ,SUTURNOVR_L10_C
 ,SUTURNOVR_L11_C
 ,SUTURNOVR_L12_C
 ,SUTURNOVR_L13_C
 ,SUTURNOVR_C1_C
 ,SUTURNOVR_C2_C
 ,SUTURNOVR_C3_C
 ,SUTURNOVR_C4_C
 ,SUTURNOVR_C5_C
 ,SUTURNOVR_C6_C
 ,SUTURNOVR_C7_C
 ,SUTURNOVR_C8_C
 ,SUTURNOVR_C9_C
 ,SUTURNOVR_C10_C
 ,SUTURNOVR_C11_C
 ,SUTURNOVR_C12_C
 ,SUTURNOVR_C13_C
 ,SUTURNOVR_O1_C
 ,SUTURNOVR_O2_C
 ,SUTURNOVR_O3_C
 ,SUTURNOVR_O4_C
 ,SUTURNOVR_O5_C
 ,SUTURNOVR_O6_C
 ,SUTURNOVR_O7_C
 ,SUTURNOVR_O8_C
 ,SUTURNOVR_O9_C
 ,SUTURNOVR_O10_C
 ,SUTURNOVR_O11_C
 ,SUTURNOVR_O12_C
 ,SUTURNOVR_O13_C
 ,SUTURNOVR_YTD_C
 ,SUTURNOVR_PTD_C
 ,SU_NOTES
 ,SU_BANK_SORT
 ,SU_BANK_AC_NO
 ,SU_BANK_AC_NAME
 ,SU_BANK_BACSREF
 ,SU_BANK_BANKNAME
 ,SU_REM_ADD_CDE
 ,SU_INV_ADD_CDE
 ,SU_DEL_ADD_CDE
 ,SU_ST_ADD_CODE
 ,SU_DATE_INV
 ,SU_DATE_PAY
 ,SU_USER_PUTIN
 ,SU_DATE_PUTIN
 ,SU_DATE_EDITED
 ,SU_USER_EDITED
 ,SU_MU_STATUS
 ,SU_LINE_DISC
 ,SU_TOT_DISC
 ,SU_SETT_DISC1
 ,SU_SETT_DISC2
 ,SU_SETT_DAYS1
 ,SU_SETT_DAYS2
 ,SU_ON_STOP
 ,SU_CREDIT_LIMIT
 ,SU_TERMS
 ,SU_DEL_CHARGE
 ,SU_DEL_CHARGE_C
 ,SU_MIN_ORDR
 ,SU_MIN_ORDR_C
 ,SU_DUE_DAYS
 ,SU_A_P_DAYS
 ,SU_DEL_CHG_PCNT
 ,SU_DUEDATE_TYPE
 ,SU_PRICE_KEY
 ,SU_ANALYSIS
 ,SU_TAX_CODE
 ,SU_BANK_ANALYS
 ,SU_ADDRESS_USER1
 ,SU_ADDRESS_USER2
 ,SU_EMAIL
 ,SU_PRIMARY
 ,SU_CURRENCY_CHANGED
 ,SU_SOURCE
 ,SU_DOC_DESTINATION
 ,SU_COUNTRY
 ,SU_DO_NOT_USE
 ,SU_LEAD_TIME
 ,SU_CIS
 ,SU_CIS_TAX_STATUS
 ,SU_CIS_UTR
 ,SU_CIS_INACTIVE
 ,SU_CIS_BUSINESS_TYPE
 ,SU_CIS_NI_NUMBER
 ,SU_CIS_COMPANY_REG_NO
 ,SU_CIS300_NAME
 ,SU_VERIFICATION_NUMBER
 ,SU_DATE_MATCHED
 ,SU_PARTNERSHIP_LINK
 ,SU_CONTRACT_AGREED
 ,SU_CIS_TITLE
 ,SU_CIS_FORENAME1
 ,SU_CIS_FORENAME2
 ,SU_CIS_SURNAME
 ,SU_INSURANCE_COMPANY
 ,SU_INSURANCE_POLICY_NO
 ,SU_INSURANCE_EXPIRY_DATE
 ,SU_INSURANCE_CHECKED
 ,SU_CITB_LEVY
 ,SU_MATCH_IN_PROGRESS
 ,SU_CURR_CREDIT_LIMIT
 ,SU_ANT_DAYS_FROM_DATES_OPT
 ,SU_COMPANY_REG_NUMBER
 ,SU_SWIFT_CODE
 ,SU_METHOD_OF_PAYMENT
)
VALUES
(
  '' -- SUCODE - VARCHAR(10)
 ,'' -- SUNAME - VARCHAR(40)
 ,'' -- SUADDRESS - VARCHAR(160)
 ,'' -- SUPOSTCODE - VARCHAR(12)
 ,'' -- SUPHONE - VARCHAR(20)
 ,'' -- SUPHONE2 - VARCHAR(20)
 ,'' -- SUFAX - VARCHAR(20)
 ,'' -- SUCONTACT - VARCHAR(30)
 ,'' -- SUSALUTE - VARCHAR(20)
 ,0 -- SU_MULTI_CURR - TINYINT(4)
 ,'' -- SU_IMPORT_CODE - VARCHAR(1)
 ,'' -- SU_COUNTRY_CODE - VARCHAR(4)
 ,'' -- SU_VAT_REG_NO - VARCHAR(15)
 ,'' -- SU_EC_DELIVERY - VARCHAR(3)
 ,'' -- SU_EC_T_NATURE - VARCHAR(2)
 ,'' -- SU_EC_T_MODE - VARCHAR(1)
 ,0 -- SUBALANCE - DOUBLE
 ,0 -- SUBALANCE_C - DOUBLE
 ,0 -- SUAGED_1 - DOUBLE
 ,0 -- SUAGED_2 - DOUBLE
 ,0 -- SUAGED_3 - DOUBLE
 ,0 -- SUAGED_4 - DOUBLE
 ,0 -- SUAGED_UNALLOC - DOUBLE
 ,'' -- SUSORT - VARCHAR(20)
 ,'' -- SUUSER1 - VARCHAR(20)
 ,'' -- SUUSER2 - VARCHAR(20)
 ,'' -- SUUSER3 - VARCHAR(20)
 ,0 -- SUUSED - TINYINT(4)
 ,0 -- SU_US1099 - TINYINT(4)
 ,0 -- SUTURNOVERPTD - DOUBLE
 ,0 -- SUTURNOVR_L1 - DOUBLE
 ,0 -- SUTURNOVR_L2 - DOUBLE
 ,0 -- SUTURNOVR_L3 - DOUBLE
 ,0 -- SUTURNOVR_L4 - DOUBLE
 ,0 -- SUTURNOVR_L5 - DOUBLE
 ,0 -- SUTURNOVR_L6 - DOUBLE
 ,0 -- SUTURNOVR_L7 - DOUBLE
 ,0 -- SUTURNOVR_L8 - DOUBLE
 ,0 -- SUTURNOVR_L9 - DOUBLE
 ,0 -- SUTURNOVR_L10 - DOUBLE
 ,0 -- SUTURNOVR_L11 - DOUBLE
 ,0 -- SUTURNOVR_L12 - DOUBLE
 ,0 -- SUTURNOVR_L13 - DOUBLE
 ,0 -- SUTURNOVR_C1 - DOUBLE
 ,0 -- SUTURNOVR_C2 - DOUBLE
 ,0 -- SUTURNOVR_C3 - DOUBLE
 ,0 -- SUTURNOVR_C4 - DOUBLE
 ,0 -- SUTURNOVR_C5 - DOUBLE
 ,0 -- SUTURNOVR_C6 - DOUBLE
 ,0 -- SUTURNOVR_C7 - DOUBLE
 ,0 -- SUTURNOVR_C8 - DOUBLE
 ,0 -- SUTURNOVR_C9 - DOUBLE
 ,0 -- SUTURNOVR_C10 - DOUBLE
 ,0 -- SUTURNOVR_C11 - DOUBLE
 ,0 -- SUTURNOVR_C12 - DOUBLE
 ,0 -- SUTURNOVR_C13 - DOUBLE
 ,0 -- SUTURNOVR_O1 - DOUBLE
 ,0 -- SUTURNOVR_O2 - DOUBLE
 ,0 -- SUTURNOVR_O3 - DOUBLE
 ,0 -- SUTURNOVR_O4 - DOUBLE
 ,0 -- SUTURNOVR_O5 - DOUBLE
 ,0 -- SUTURNOVR_O6 - DOUBLE
 ,0 -- SUTURNOVR_O7 - DOUBLE
 ,0 -- SUTURNOVR_O8 - DOUBLE
 ,0 -- SUTURNOVR_O9 - DOUBLE
 ,0 -- SUTURNOVR_O10 - DOUBLE
 ,0 -- SUTURNOVR_O11 - DOUBLE
 ,0 -- SUTURNOVR_O12 - DOUBLE
 ,0 -- SUTURNOVR_O13 - DOUBLE
 ,0 -- SUTURNOVERYTD - DOUBLE
 ,'' -- SUCURRENCYCODE - VARCHAR(6)
 ,0 -- SUTURNOVR_L1_C - DOUBLE
 ,0 -- SUTURNOVR_L2_C - DOUBLE
 ,0 -- SUTURNOVR_L3_C - DOUBLE
 ,0 -- SUTURNOVR_L4_C - DOUBLE
 ,0 -- SUTURNOVR_L5_C - DOUBLE
 ,0 -- SUTURNOVR_L6_C - DOUBLE
 ,0 -- SUTURNOVR_L7_C - DOUBLE
 ,0 -- SUTURNOVR_L8_C - DOUBLE
 ,0 -- SUTURNOVR_L9_C - DOUBLE
 ,0 -- SUTURNOVR_L10_C - DOUBLE
 ,0 -- SUTURNOVR_L11_C - DOUBLE
 ,0 -- SUTURNOVR_L12_C - DOUBLE
 ,0 -- SUTURNOVR_L13_C - DOUBLE
 ,0 -- SUTURNOVR_C1_C - DOUBLE
 ,0 -- SUTURNOVR_C2_C - DOUBLE
 ,0 -- SUTURNOVR_C3_C - DOUBLE
 ,0 -- SUTURNOVR_C4_C - DOUBLE
 ,0 -- SUTURNOVR_C5_C - DOUBLE
 ,0 -- SUTURNOVR_C6_C - DOUBLE
 ,0 -- SUTURNOVR_C7_C - DOUBLE
 ,0 -- SUTURNOVR_C8_C - DOUBLE
 ,0 -- SUTURNOVR_C9_C - DOUBLE
 ,0 -- SUTURNOVR_C10_C - DOUBLE
 ,0 -- SUTURNOVR_C11_C - DOUBLE
 ,0 -- SUTURNOVR_C12_C - DOUBLE
 ,0 -- SUTURNOVR_C13_C - DOUBLE
 ,0 -- SUTURNOVR_O1_C - DOUBLE
 ,0 -- SUTURNOVR_O2_C - DOUBLE
 ,0 -- SUTURNOVR_O3_C - DOUBLE
 ,0 -- SUTURNOVR_O4_C - DOUBLE
 ,0 -- SUTURNOVR_O5_C - DOUBLE
 ,0 -- SUTURNOVR_O6_C - DOUBLE
 ,0 -- SUTURNOVR_O7_C - DOUBLE
 ,0 -- SUTURNOVR_O8_C - DOUBLE
 ,0 -- SUTURNOVR_O9_C - DOUBLE
 ,0 -- SUTURNOVR_O10_C - DOUBLE
 ,0 -- SUTURNOVR_O11_C - DOUBLE
 ,0 -- SUTURNOVR_O12_C - DOUBLE
 ,0 -- SUTURNOVR_O13_C - DOUBLE
 ,0 -- SUTURNOVR_YTD_C - DOUBLE
 ,0 -- SUTURNOVR_PTD_C - DOUBLE
 ,'' -- SU_NOTES - TEXT
 ,'' -- SU_BANK_SORT - VARCHAR(10)
 ,'' -- SU_BANK_AC_NO - VARCHAR(18)
 ,'' -- SU_BANK_AC_NAME - VARCHAR(30)
 ,'' -- SU_BANK_BACSREF - VARCHAR(18)
 ,'' -- SU_BANK_BANKNAME - VARCHAR(25)
 ,0 -- SU_REM_ADD_CDE - DOUBLE
 ,0 -- SU_INV_ADD_CDE - DOUBLE
 ,0 -- SU_DEL_ADD_CDE - DOUBLE
 ,0 -- SU_ST_ADD_CODE - DOUBLE
 ,NOW() -- SU_DATE_INV - DATETIME
 ,NOW() -- SU_DATE_PAY - DATETIME
 ,'' -- SU_USER_PUTIN - VARCHAR(4)
 ,NOW() -- SU_DATE_PUTIN - DATETIME
 ,NOW() -- SU_DATE_EDITED - DATETIME
 ,'' -- SU_USER_EDITED - VARCHAR(4)
 ,'' -- SU_MU_STATUS - VARCHAR(1)
 ,0 -- SU_LINE_DISC - DOUBLE
 ,0 -- SU_TOT_DISC - DOUBLE
 ,0 -- SU_SETT_DISC1 - DOUBLE
 ,0 -- SU_SETT_DISC2 - DOUBLE
 ,0 -- SU_SETT_DAYS1 - DOUBLE
 ,0 -- SU_SETT_DAYS2 - DOUBLE
 ,0 -- SU_ON_STOP - TINYINT(4)
 ,0 -- SU_CREDIT_LIMIT - DOUBLE
 ,'' -- SU_TERMS - VARCHAR(40)
 ,0 -- SU_DEL_CHARGE - DOUBLE
 ,0 -- SU_DEL_CHARGE_C - DOUBLE
 ,0 -- SU_MIN_ORDR - DOUBLE
 ,0 -- SU_MIN_ORDR_C - DOUBLE
 ,0 -- SU_DUE_DAYS - DOUBLE
 ,0 -- SU_A_P_DAYS - DOUBLE
 ,0 -- SU_DEL_CHG_PCNT - DOUBLE
 ,0 -- SU_DUEDATE_TYPE - TINYINT(4)
 ,0 -- SU_PRICE_KEY - TINYINT(4)
 ,'' -- SU_ANALYSIS - VARCHAR(25)
 ,'' -- SU_TAX_CODE - VARCHAR(4)
 ,'' -- SU_BANK_ANALYS - VARCHAR(25)
 ,'' -- SU_ADDRESS_USER1 - VARCHAR(30)
 ,'' -- SU_ADDRESS_USER2 - VARCHAR(30)
 ,'' -- SU_EMAIL - VARCHAR(64)
 ,0 -- SU_PRIMARY - DOUBLE NOT NULL
 ,0 -- SU_CURRENCY_CHANGED - TINYINT(4)
 ,'' -- SU_SOURCE - VARCHAR(1)
 ,'' -- SU_DOC_DESTINATION - VARCHAR(10)
 ,'' -- SU_COUNTRY - VARCHAR(35)
 ,0 -- SU_DO_NOT_USE - TINYINT(4) NOT NULL
 ,0 -- SU_LEAD_TIME - INT(11)
 ,0 -- SU_CIS - TINYINT(4)
 ,0 -- SU_CIS_TAX_STATUS - TINYINT(4)
 ,'' -- SU_CIS_UTR - VARCHAR(10)
 ,0 -- SU_CIS_INACTIVE - TINYINT(4)
 ,0 -- SU_CIS_BUSINESS_TYPE - TINYINT(4)
 ,'' -- SU_CIS_NI_NUMBER - VARCHAR(9)
 ,'' -- SU_CIS_COMPANY_REG_NO - VARCHAR(8)
 ,'' -- SU_CIS300_NAME - VARCHAR(56)
 ,'' -- SU_VERIFICATION_NUMBER - VARCHAR(13)
 ,NOW() -- SU_DATE_MATCHED - DATETIME
 ,'' -- SU_PARTNERSHIP_LINK - VARCHAR(10)
 ,0 -- SU_CONTRACT_AGREED - TINYINT(4)
 ,'' -- SU_CIS_TITLE - VARCHAR(4)
 ,'' -- SU_CIS_FORENAME1 - VARCHAR(35)
 ,'' -- SU_CIS_FORENAME2 - VARCHAR(35)
 ,'' -- SU_CIS_SURNAME - VARCHAR(35)
 ,'' -- SU_INSURANCE_COMPANY - VARCHAR(40)
 ,'' -- SU_INSURANCE_POLICY_NO - VARCHAR(25)
 ,NOW() -- SU_INSURANCE_EXPIRY_DATE - DATETIME
 ,0 -- SU_INSURANCE_CHECKED - TINYINT(4)
 ,0 -- SU_CITB_LEVY - TINYINT(4)
 ,0 -- SU_MATCH_IN_PROGRESS - TINYINT(4)
 ,0 -- SU_CURR_CREDIT_LIMIT - DOUBLE
 ,0 -- SU_ANT_DAYS_FROM_DATES_OPT - TINYINT(4)
 ,'' -- SU_COMPANY_REG_NUMBER - VARCHAR(20)
 ,'' -- SU_SWIFT_CODE - VARCHAR(11)
 ,'' -- SU_METHOD_OF_PAYMENT - VARCHAR(20)
)