INSERT INTO sjbrett_AdvAcct.PL_TRANSACTIONS
(
  PT_TRANTYPE
 ,PT_HEADER_REF
 ,PT_INTERNAL_REF
 ,PT_DESCRIPTION
 ,PT_DATE
 ,PT_DUEDATE
 ,PT_ANTICPAYDATE
 ,PT_SETT_DISC1
 ,PT_SETT_DISC2
 ,PT_SETT_DAYS1
 ,PT_SETT_DAYS2
 ,PT_NETT
 ,PT_VAT
 ,PT_GROSS
 ,PT_UNALLOCATED
 ,PT_BATCH_FLAG
 ,PT_BATCH_REF
 ,PT_ARCHIVE_FLAG
 ,PT_ALOC_POINTER
 ,PT_ORIGIN
 ,PT_REVALUE_RATE
 ,PT_CURRENCYRATE
 ,PT_CURRENCYCODE
 ,PT_CURR_VALU
 ,PT_CURR_UNAL
 ,PT_CURRENCYRTCH
 ,PT_CURRENCYEXDF
 ,PT_ACQUISTN_TAX
 ,PT_IMPORT_CODE
 ,PT_REVALUED
 ,PT_EC_DEL_TERMS
 ,PT_EC_T_NATURE
 ,PT_EC_T_MODE
 ,PT_REVALUE_DATE
 ,PT_PAYMENT_FLAG
 ,PT_QUERY_FLAG
 ,PT_DONOTCHASE
 ,PT_CHASE1
 ,PT_CHASE2
 ,PT_CHASE3
 ,PT_PERIODNUMBER
 ,PT_YEAR
 ,PT_ALLOC_USER1
 ,PT_ALLOC_USER2
 ,PT_ALLOC_USER3
 ,PT_ALLOC_DATE1
 ,PT_ALLOC_DATE2
 ,PT_ALLOC_DATE3
 ,PT_ALLOC_VALU1
 ,PT_ALLOC_VALU2
 ,PT_ALLOC_VALU3
 ,PT_ALLOC_REF1
 ,PT_ALLOC_REF2
 ,PT_ALLOC_REF3
 ,PT_ALLOC_PERIOD
 ,PT_ALLOC_YEAR
 ,PT_T_DISCVAL
 ,PT_T_DISCVAL_C
 ,PT_L_DISCVAL
 ,PT_L_DISCVAL_C
 ,PT_USER_PUTIN
 ,PT_DATE_PUTIN
 ,PT_MU_STATUS
 ,PT_USER1
 ,PT_USER2
 ,PT_USER3
 ,PT_BATCH_POSTED
 ,PT_CON_REFTYPE
 ,PT_ORDER_NUMBER
 ,PT_COPYSUPP
 ,PT_REBUILDNUM
 ,PT_PRIMARY
 ,PT_HEADER_KEY
 ,PT_SUB_LEDGER
 ,PT_ALLOC_CBREF
 ,PT_CENTRALISED
 ,PT_PAYLIST_VALUE
 ,PT_PAYLIST_SETT_DISC
 ,PT_PAYLIST_REF
 ,PT_INVREG_FLAG
 ,PT_INVREG_STATUS
 ,PT_INVREG_TYPE
 ,PT_INVREG_OVERIDE
 ,PT_INVREG_APPROVER1
 ,PT_INVREG_APPROVER2
 ,PT_INVREG_APPROVER3
 ,PT_INVREG_APPROVEKEY1
 ,PT_INVREG_APPROVEKEY2
 ,PT_INVREG_APPROVEKEY3
 ,PT_INVREG_APPROVEDATE1
 ,PT_INVREG_APPROVEDATE2
 ,PT_INVREG_APPROVEDATE3
 ,PT_INVREG_MATCHEDUSER
 ,PT_INVREG_MATCHEDDATE
 ,PT_INVREG_MATCHEDKEY
 ,PT_INVREG_APPROVESTATUS
 ,PT_PAY_STAGE1_USER
 ,PT_PAY_STAGE2_USER
 ,PT_PAY_STAGE_STATUS
 ,PT_RECONCILED
 ,PT_ALLOC_XREF
 ,PT_NETT_BASE2
 ,PT_VAT_BASE2
 ,PT_GROSS_BASE2
 ,PT_L_DISC_BASE2
 ,PT_T_DISC_BASE2
 ,PT_BASE2_RATE
 ,PT_TRI_RATE1
 ,PT_BASE2_RATECHNG
 ,PT_TRI_RATECHNG1
 ,PT_ACQUISTN_BASE2
 ,PT_RND_DIFF_BASE1
 ,PT_CURR_NETT
 ,PT_CURR_TAX
 ,PT_CURR_TYPE
 ,PT_TRI_RATE2
 ,PT_TRI_RATECHNG2
 ,PT_RND_DIFF_POSTED
 ,PT_SPCL_TRANTYPE
 ,PT_HEADER_REF2
 ,PT_SRV_STATUS
 ,PT_RND_DIFF_BASE2
 ,PT_SOURCE
 ,PT_TRAN_OPTIONS
 ,PT_SURVEYOR
 ,PT_CIS_SENT_TO
 ,PT_CIS_SENT_DATE
 ,PT_CIS_AUTHORISED
 ,PT_CIS_AUTHORISED_DATE
 ,PT_CIS_PAYEE_NAME
 ,PT_CIS300_FLAG
 ,PT_PARTNER
 ,PT_DATE_RECEIVED
 ,PT_INVREG_TRAN_OPTIONS
 ,PT_NOM_CAT_LINK
 ,PT_YEAR_LINK
 ,PT_ALLOC_YEAR_LINK
 ,PT_BACS_LAYOUT
 ,PT_REVERSE_SERVICE_VAT
 ,PT_REVERSE_SERVICE_VAT_BASE2
 ,PT_WFF_APPROVAL_STATUS
 ,PT_CURR_ACQUISTN
)
VALUES
(
  '' -- PT_TRANTYPE - VARCHAR(3)
 ,'' -- PT_HEADER_REF - VARCHAR(25)
 ,0 -- PT_INTERNAL_REF - DOUBLE
 ,'' -- PT_DESCRIPTION - VARCHAR(30)
 ,NOW() -- PT_DATE - DATETIME
 ,NOW() -- PT_DUEDATE - DATETIME
 ,NOW() -- PT_ANTICPAYDATE - DATETIME
 ,0 -- PT_SETT_DISC1 - DOUBLE
 ,0 -- PT_SETT_DISC2 - DOUBLE
 ,0 -- PT_SETT_DAYS1 - DOUBLE
 ,0 -- PT_SETT_DAYS2 - DOUBLE
 ,0 -- PT_NETT - DOUBLE
 ,0 -- PT_VAT - DOUBLE
 ,0 -- PT_GROSS - DOUBLE
 ,0 -- PT_UNALLOCATED - DOUBLE
 ,0 -- PT_BATCH_FLAG - TINYINT(4)
 ,'' -- PT_BATCH_REF - VARCHAR(10)
 ,0 -- PT_ARCHIVE_FLAG - TINYINT(4)
 ,'' -- PT_ALOC_POINTER - VARCHAR(11)
 ,'' -- PT_ORIGIN - VARCHAR(2)
 ,0 -- PT_REVALUE_RATE - DOUBLE
 ,0 -- PT_CURRENCYRATE - DOUBLE
 ,'' -- PT_CURRENCYCODE - VARCHAR(4)
 ,0 -- PT_CURR_VALU - DOUBLE
 ,0 -- PT_CURR_UNAL - DOUBLE
 ,0 -- PT_CURRENCYRTCH - TINYINT(4)
 ,0 -- PT_CURRENCYEXDF - DOUBLE
 ,0 -- PT_ACQUISTN_TAX - DOUBLE
 ,'' -- PT_IMPORT_CODE - VARCHAR(1)
 ,0 -- PT_REVALUED - DOUBLE
 ,'' -- PT_EC_DEL_TERMS - VARCHAR(3)
 ,'' -- PT_EC_T_NATURE - VARCHAR(2)
 ,'' -- PT_EC_T_MODE - VARCHAR(1)
 ,NOW() -- PT_REVALUE_DATE - DATETIME
 ,'' -- PT_PAYMENT_FLAG - VARCHAR(1)
 ,0 -- PT_QUERY_FLAG - TINYINT(4)
 ,0 -- PT_DONOTCHASE - TINYINT(4)
 ,0 -- PT_CHASE1 - TINYINT(4)
 ,0 -- PT_CHASE2 - TINYINT(4)
 ,0 -- PT_CHASE3 - TINYINT(4)
 ,0 -- PT_PERIODNUMBER - TINYINT(4)
 ,'' -- PT_YEAR - VARCHAR(1)
 ,'' -- PT_ALLOC_USER1 - VARCHAR(4)
 ,'' -- PT_ALLOC_USER2 - VARCHAR(4)
 ,'' -- PT_ALLOC_USER3 - VARCHAR(4)
 ,NOW() -- PT_ALLOC_DATE1 - DATETIME
 ,NOW() -- PT_ALLOC_DATE2 - DATETIME
 ,NOW() -- PT_ALLOC_DATE3 - DATETIME
 ,0 -- PT_ALLOC_VALU1 - DOUBLE
 ,0 -- PT_ALLOC_VALU2 - DOUBLE
 ,0 -- PT_ALLOC_VALU3 - DOUBLE
 ,'' -- PT_ALLOC_REF1 - VARCHAR(10)
 ,'' -- PT_ALLOC_REF2 - VARCHAR(10)
 ,'' -- PT_ALLOC_REF3 - VARCHAR(10)
 ,0 -- PT_ALLOC_PERIOD - TINYINT(4)
 ,'' -- PT_ALLOC_YEAR - VARCHAR(1)
 ,0 -- PT_T_DISCVAL - DOUBLE
 ,0 -- PT_T_DISCVAL_C - DOUBLE
 ,0 -- PT_L_DISCVAL - DOUBLE
 ,0 -- PT_L_DISCVAL_C - DOUBLE
 ,'' -- PT_USER_PUTIN - VARCHAR(4)
 ,NOW() -- PT_DATE_PUTIN - DATETIME
 ,'' -- PT_MU_STATUS - VARCHAR(1)
 ,'' -- PT_USER1 - VARCHAR(20)
 ,'' -- PT_USER2 - VARCHAR(20)
 ,'' -- PT_USER3 - VARCHAR(20)
 ,'' -- PT_BATCH_POSTED - VARCHAR(1)
 ,'' -- PT_CON_REFTYPE - VARCHAR(26)
 ,'' -- PT_ORDER_NUMBER - VARCHAR(10)
 ,'' -- PT_COPYSUPP - VARCHAR(10)
 ,0 -- PT_REBUILDNUM - DOUBLE
 ,0 -- PT_PRIMARY - DOUBLE NOT NULL
 ,'' -- PT_HEADER_KEY - VARCHAR(20)
 ,'' -- PT_SUB_LEDGER - VARCHAR(10)
 ,'' -- PT_ALLOC_CBREF - VARCHAR(10)
 ,0 -- PT_CENTRALISED - TINYINT(4)
 ,0 -- PT_PAYLIST_VALUE - DOUBLE
 ,0 -- PT_PAYLIST_SETT_DISC - DOUBLE
 ,'' -- PT_PAYLIST_REF - VARCHAR(10)
 ,0 -- PT_INVREG_FLAG - TINYINT(4)
 ,'' -- PT_INVREG_STATUS - VARCHAR(1)
 ,'' -- PT_INVREG_TYPE - VARCHAR(1)
 ,'' -- PT_INVREG_OVERIDE - VARCHAR(4)
 ,'' -- PT_INVREG_APPROVER1 - VARCHAR(4)
 ,'' -- PT_INVREG_APPROVER2 - VARCHAR(4)
 ,'' -- PT_INVREG_APPROVER3 - VARCHAR(4)
 ,'' -- PT_INVREG_APPROVEKEY1 - VARCHAR(1)
 ,'' -- PT_INVREG_APPROVEKEY2 - VARCHAR(1)
 ,'' -- PT_INVREG_APPROVEKEY3 - VARCHAR(1)
 ,NOW() -- PT_INVREG_APPROVEDATE1 - DATETIME
 ,NOW() -- PT_INVREG_APPROVEDATE2 - DATETIME
 ,NOW() -- PT_INVREG_APPROVEDATE3 - DATETIME
 ,'' -- PT_INVREG_MATCHEDUSER - VARCHAR(4)
 ,NOW() -- PT_INVREG_MATCHEDDATE - DATETIME
 ,'' -- PT_INVREG_MATCHEDKEY - VARCHAR(1)
 ,'' -- PT_INVREG_APPROVESTATUS - VARCHAR(3)
 ,'' -- PT_PAY_STAGE1_USER - VARCHAR(4)
 ,'' -- PT_PAY_STAGE2_USER - VARCHAR(4)
 ,0 -- PT_PAY_STAGE_STATUS - TINYINT(4)
 ,0 -- PT_RECONCILED - TINYINT(4)
 ,'' -- PT_ALLOC_XREF - VARCHAR(15)
 ,0 -- PT_NETT_BASE2 - DOUBLE
 ,0 -- PT_VAT_BASE2 - DOUBLE
 ,0 -- PT_GROSS_BASE2 - DOUBLE
 ,0 -- PT_L_DISC_BASE2 - DOUBLE
 ,0 -- PT_T_DISC_BASE2 - DOUBLE
 ,0 -- PT_BASE2_RATE - DOUBLE
 ,0 -- PT_TRI_RATE1 - DOUBLE
 ,0 -- PT_BASE2_RATECHNG - TINYINT(4)
 ,0 -- PT_TRI_RATECHNG1 - TINYINT(4)
 ,0 -- PT_ACQUISTN_BASE2 - DOUBLE
 ,0 -- PT_RND_DIFF_BASE1 - DOUBLE
 ,0 -- PT_CURR_NETT - DOUBLE
 ,0 -- PT_CURR_TAX - DOUBLE
 ,'' -- PT_CURR_TYPE - VARCHAR(1)
 ,0 -- PT_TRI_RATE2 - DOUBLE
 ,0 -- PT_TRI_RATECHNG2 - TINYINT(4)
 ,0 -- PT_RND_DIFF_POSTED - TINYINT(4)
 ,'' -- PT_SPCL_TRANTYPE - VARCHAR(20)
 ,'' -- PT_HEADER_REF2 - VARCHAR(10)
 ,0 -- PT_SRV_STATUS - TINYINT(4)
 ,0 -- PT_RND_DIFF_BASE2 - DOUBLE
 ,'' -- PT_SOURCE - VARCHAR(1)
 ,'' -- PT_TRAN_OPTIONS - VARCHAR(30)
 ,'' -- PT_SURVEYOR - VARCHAR(30)
 ,'' -- PT_CIS_SENT_TO - VARCHAR(30)
 ,NOW() -- PT_CIS_SENT_DATE - DATETIME
 ,0 -- PT_CIS_AUTHORISED - TINYINT(4)
 ,NOW() -- PT_CIS_AUTHORISED_DATE - DATETIME
 ,'' -- PT_CIS_PAYEE_NAME - VARCHAR(40)
 ,0 -- PT_CIS300_FLAG - TINYINT(4)
 ,'' -- PT_PARTNER - VARCHAR(10)
 ,NOW() -- PT_DATE_RECEIVED - DATETIME
 ,'' -- PT_INVREG_TRAN_OPTIONS - VARCHAR(6)
 ,0 -- PT_NOM_CAT_LINK - INT(11)
 ,0 -- PT_YEAR_LINK - INT(11)
 ,0 -- PT_ALLOC_YEAR_LINK - INT(11)
 ,0 -- PT_BACS_LAYOUT - TINYINT(4)
 ,0 -- PT_REVERSE_SERVICE_VAT - DOUBLE NOT NULL
 ,0 -- PT_REVERSE_SERVICE_VAT_BASE2 - DOUBLE NOT NULL
 ,0 -- PT_WFF_APPROVAL_STATUS - INT(11)
 ,0 -- PT_CURR_ACQUISTN - DOUBLE NOT NULL
)