INSERT INTO sjbrett_AdvAcct.SL_ADDRESSES
(
  AD_ACC_CODE
 ,AD_CODE
 ,AD_CON_CODE
 ,AD_ADDRESS
 ,AD_POSTCODE
 ,AD_HOME_PHONE
 ,AD_EXTENSION
 ,AD_PHONE
 ,AD_FAX
 ,AD_MOBILE
 ,AD_E_MAIL
 ,AD_CONTACT
 ,AD_CONT_SALUTE
 ,AD_INV_ADDRESS
 ,AD_DEL_ADDRESS
 ,AD_STAT_ADDRESS
 ,AD_PROSPECT
 ,AD_ACCOUNTNAME
 ,AD_NOTE
 ,AD_CON_TITLE
 ,AD_CON_INITIALS
 ,AD_CON_SURNAME
 ,AD_CON_JOB
 ,AD_CON_FNAME
 ,AD_DEALERCODE
 ,AD_USERTEXT1
 ,AD_USERTEXT2
 ,AD_USERDATE1
 ,AD_USERNUM1
 ,AD_USERFLAG1
 ,AD_USERFLAG2
 ,AD_USERFLAG3
 ,AD_USERFLAG4
 ,AD_EDITED_TIME
 ,AD_RECALL_TIME
 ,AD_USER_EDITED
 ,AD_USER_PUTIN
 ,AD_DATE_PUTIN
 ,AD_DATE_EDITED
 ,SL_AD_PRIMARY
 ,AD_USERTEXT3
 ,AD_USERTEXT4
 ,AD_USERTEXT5
 ,AD_USERTEXT6
 ,AD_USERDATE2
 ,AD_USERDATE3
 ,AD_USERNUM2
 ,AD_USERNUM3
 ,AD_USERTEXT7
 ,AD_USERTEXT8
 ,AD_USERTEXT9
 ,AD_USERTEXT10
 ,AD_ADDRESS_USER1
 ,AD_ADDRESS_USER2
 ,AD_USER_ALOC
 ,AD_ANALYSIS
 ,AD_LEVEL
 ,AD_GROUP
 ,AD_DEL_ADDRESS_2
 ,AD_DLR_NOTIFICATION
 ,AD_DLR_NOTIFICATION_DATE
 ,AD_CNT_NOTIFICATION
 ,AD_CNT_NOTIFICATION_DATE
 ,AD_SOURCE
 ,AD_CC_EMAIL
 ,AD_COUNTRY
 ,AD_DO_NOT_USE
 ,AD_COUNTRY_CODE
 ,AD_EXPORT_CODE
 ,AD_BRANCH_ID
 ,AD_VAT_REG_NO
 ,AD_EC_DELIVERY
 ,AD_EC_T_NATURE
 ,AD_EC_T_MODE
 ,AD_USED_FLAG
 ,AD_DO_NOT_EMAIL
 ,AD_DATE_ALLOCATED
 ,AD_DELIVERY_ROUTE
)
VALUES
(
  '' -- AD_ACC_CODE - VARCHAR(10)
 ,0 -- AD_CODE - DOUBLE
 ,'' -- AD_CON_CODE - VARCHAR(16)
 ,'' -- AD_ADDRESS - VARCHAR(160)
 ,'' -- AD_POSTCODE - VARCHAR(12)
 ,'' -- AD_HOME_PHONE - VARCHAR(20)
 ,'' -- AD_EXTENSION - VARCHAR(20)
 ,'' -- AD_PHONE - VARCHAR(20)
 ,'' -- AD_FAX - VARCHAR(20)
 ,'' -- AD_MOBILE - VARCHAR(20)
 ,'' -- AD_E_MAIL - VARCHAR(64)
 ,'' -- AD_CONTACT - VARCHAR(30)
 ,'' -- AD_CONT_SALUTE - VARCHAR(20)
 ,0 -- AD_INV_ADDRESS - TINYINT(4)
 ,0 -- AD_DEL_ADDRESS - TINYINT(4)
 ,0 -- AD_STAT_ADDRESS - TINYINT(4)
 ,'' -- AD_PROSPECT - VARCHAR(1)
 ,0 -- AD_ACCOUNTNAME - TINYINT(4)
 ,'' -- AD_NOTE - TEXT
 ,'' -- AD_CON_TITLE - VARCHAR(5)
 ,'' -- AD_CON_INITIALS - VARCHAR(15)
 ,'' -- AD_CON_SURNAME - VARCHAR(30)
 ,'' -- AD_CON_JOB - VARCHAR(35)
 ,'' -- AD_CON_FNAME - VARCHAR(20)
 ,'' -- AD_DEALERCODE - VARCHAR(10)
 ,'' -- AD_USERTEXT1 - VARCHAR(20)
 ,'' -- AD_USERTEXT2 - VARCHAR(20)
 ,NOW() -- AD_USERDATE1 - DATETIME
 ,0 -- AD_USERNUM1 - DOUBLE
 ,0 -- AD_USERFLAG1 - TINYINT(4)
 ,0 -- AD_USERFLAG2 - TINYINT(4)
 ,0 -- AD_USERFLAG3 - TINYINT(4)
 ,0 -- AD_USERFLAG4 - TINYINT(4)
 ,NOW() -- AD_EDITED_TIME - DATETIME
 ,NOW() -- AD_RECALL_TIME - DATETIME
 ,'' -- AD_USER_EDITED - VARCHAR(4)
 ,'' -- AD_USER_PUTIN - VARCHAR(4)
 ,NOW() -- AD_DATE_PUTIN - DATETIME
 ,NOW() -- AD_DATE_EDITED - DATETIME
 ,0 -- SL_AD_PRIMARY - DOUBLE NOT NULL
 ,'' -- AD_USERTEXT3 - VARCHAR(20)
 ,'' -- AD_USERTEXT4 - VARCHAR(20)
 ,'' -- AD_USERTEXT5 - VARCHAR(100)
 ,'' -- AD_USERTEXT6 - VARCHAR(100)
 ,NOW() -- AD_USERDATE2 - DATETIME
 ,NOW() -- AD_USERDATE3 - DATETIME
 ,0 -- AD_USERNUM2 - DOUBLE
 ,0 -- AD_USERNUM3 - DOUBLE
 ,'' -- AD_USERTEXT7 - VARCHAR(20)
 ,'' -- AD_USERTEXT8 - VARCHAR(20)
 ,'' -- AD_USERTEXT9 - VARCHAR(20)
 ,'' -- AD_USERTEXT10 - VARCHAR(20)
 ,'' -- AD_ADDRESS_USER1 - VARCHAR(30)
 ,'' -- AD_ADDRESS_USER2 - VARCHAR(30)
 ,'' -- AD_USER_ALOC - VARCHAR(4)
 ,'' -- AD_ANALYSIS - VARCHAR(25)
 ,0 -- AD_LEVEL - INT(11)
 ,'' -- AD_GROUP - VARCHAR(10)
 ,0 -- AD_DEL_ADDRESS_2 - TINYINT(4)
 ,0 -- AD_DLR_NOTIFICATION - TINYINT(4)
 ,NOW() -- AD_DLR_NOTIFICATION_DATE - DATETIME
 ,0 -- AD_CNT_NOTIFICATION - TINYINT(4)
 ,NOW() -- AD_CNT_NOTIFICATION_DATE - DATETIME
 ,'' -- AD_SOURCE - VARCHAR(1)
 ,'' -- AD_CC_EMAIL - VARCHAR(64)
 ,'' -- AD_COUNTRY - VARCHAR(35)
 ,0 -- AD_DO_NOT_USE - TINYINT(4)
 ,'' -- AD_COUNTRY_CODE - VARCHAR(4)
 ,'' -- AD_EXPORT_CODE - VARCHAR(1)
 ,'' -- AD_BRANCH_ID - VARCHAR(3)
 ,'' -- AD_VAT_REG_NO - VARCHAR(21)
 ,'' -- AD_EC_DELIVERY - VARCHAR(3)
 ,'' -- AD_EC_T_NATURE - VARCHAR(2)
 ,'' -- AD_EC_T_MODE - VARCHAR(1)
 ,0 -- AD_USED_FLAG - TINYINT(4)
 ,0 -- AD_DO_NOT_EMAIL - TINYINT(4) NOT NULL
 ,NOW() -- AD_DATE_ALLOCATED - DATETIME
 ,'' -- AD_DELIVERY_ROUTE - VARCHAR(20)
)