INSERT INTO sjbrett_AdvAcct.SL_ACCOUNTS
(
  CUCODE
 ,CUNAME
 ,CUADDRESS
 ,CUPOSTCODE
 ,CUPHONE
 ,CUPHONE2
 ,CUFAX
 ,CUPROSCODE
 ,CUCONTACT
 ,CUSALUTE
 ,CU_PRO_CONDATE
 ,CU_EXPORT_CODE
 ,CU_COUNTRY_CODE
 ,CU_VAT_REG_NO
 ,CU_EC_DELIVERY
 ,CU_EC_T_NATURE
 ,CU_EC_T_MODE
 ,CUBALANCE
 ,CUBALANCE_C
 ,CUAGED_1
 ,CUAGED_2
 ,CUAGED_3
 ,CUAGED_4
 ,CUAGED_UNALLOC
 ,CUSORT
 ,CUUSER1
 ,CUUSER2
 ,CUUSER3
 ,CUTURNOVERPTD
 ,CUTURNOVR_L1
 ,CUTURNOVR_L2
 ,CUTURNOVR_L3
 ,CUTURNOVR_L4
 ,CUTURNOVR_L5
 ,CUTURNOVR_L6
 ,CUTURNOVR_L7
 ,CUTURNOVR_L8
 ,CUTURNOVR_L9
 ,CUTURNOVR_L10
 ,CUTURNOVR_L11
 ,CUTURNOVR_L12
 ,CUTURNOVR_L13
 ,CUTURNOVR_C1
 ,CUTURNOVR_C2
 ,CUTURNOVR_C3
 ,CUTURNOVR_C4
 ,CUTURNOVR_C5
 ,CUTURNOVR_C6
 ,CUTURNOVR_C7
 ,CUTURNOVR_C8
 ,CUTURNOVR_C9
 ,CUTURNOVR_C10
 ,CUTURNOVR_C11
 ,CUTURNOVR_C12
 ,CUTURNOVR_C13
 ,CUTURNOVR_O1
 ,CUTURNOVR_O2
 ,CUTURNOVR_O3
 ,CUTURNOVR_O4
 ,CUTURNOVR_O5
 ,CUTURNOVR_O6
 ,CUTURNOVR_O7
 ,CUTURNOVR_O8
 ,CUTURNOVR_O9
 ,CUTURNOVR_O10
 ,CUTURNOVR_O11
 ,CUTURNOVR_O12
 ,CUTURNOVR_O13
 ,CUTURNOVERYTD
 ,CUCURRENCYCODE
 ,CUTURNOVR_L1_C
 ,CUTURNOVR_L2_C
 ,CUTURNOVR_L3_C
 ,CUTURNOVR_L4_C
 ,CUTURNOVR_L5_C
 ,CUTURNOVR_L6_C
 ,CUTURNOVR_L7_C
 ,CUTURNOVR_L8_C
 ,CUTURNOVR_L9_C
 ,CUTURNOVR_L10_C
 ,CUTURNOVR_L11_C
 ,CUTURNOVR_L12_C
 ,CUTURNOVR_L13_C
 ,CUTURNOVR_C1_C
 ,CUTURNOVR_C2_C
 ,CUTURNOVR_C3_C
 ,CUTURNOVR_C4_C
 ,CUTURNOVR_C5_C
 ,CUTURNOVR_C6_C
 ,CUTURNOVR_C7_C
 ,CUTURNOVR_C8_C
 ,CUTURNOVR_C9_C
 ,CUTURNOVR_C10_C
 ,CUTURNOVR_C11_C
 ,CUTURNOVR_C12_C
 ,CUTURNOVR_C13_C
 ,CUTURNOVR_O1_C
 ,CUTURNOVR_O2_C
 ,CUTURNOVR_O3_C
 ,CUTURNOVR_O4_C
 ,CUTURNOVR_O5_C
 ,CUTURNOVR_O6_C
 ,CUTURNOVR_O7_C
 ,CUTURNOVR_O8_C
 ,CUTURNOVR_O9_C
 ,CUTURNOVR_O10_C
 ,CUTURNOVR_O11_C
 ,CUTURNOVR_O12_C
 ,CUTURNOVR_O13_C
 ,CUTURNOVR_YTD_C
 ,CUTURNOVR_PTD_C
 ,CU_COSTVAL_1
 ,CU_COSTVAL_2
 ,CU_COSTVAL_3
 ,CU_COSTVAL_4
 ,CU_COSTVAL_5
 ,CU_COSTVAL_6
 ,CU_COSTVAL_7
 ,CU_COSTVAL_8
 ,CU_COSTVAL_9
 ,CU_COSTVAL_10
 ,CU_COSTVAL_11
 ,CU_COSTVAL_12
 ,CU_COSTVAL_13
 ,CU_SALEVAL_1
 ,CU_SALEVAL_2
 ,CU_SALEVAL_3
 ,CU_SALEVAL_4
 ,CU_SALEVAL_5
 ,CU_SALEVAL_6
 ,CU_SALEVAL_7
 ,CU_SALEVAL_8
 ,CU_SALEVAL_9
 ,CU_SALEVAL_10
 ,CU_COSTVAL_PTD
 ,CU_COSTVAL_YTD
 ,CU_SALEVAL_PTD
 ,CU_SALEVAL_YTD
 ,CU_COSTVALUE
 ,CU_SALEVALUE
 ,CU_SALEVAL_11
 ,CU_SALEVAL_12
 ,CU_SALEVAL_13
 ,CU_USERDATE1
 ,CU_USERDATE2
 ,CU_NOTES
 ,CU_INV_ADD_CDE
 ,CU_DEL_ADD_CDE
 ,CU_STAT_ADD_CDE
 ,CU_DATE_INV
 ,CU_DATE_PAY
 ,CU_USER_PUTIN
 ,CU_DATE_PUTIN
 ,CU_DATE_EDITED
 ,CU_USER_EDITED
 ,CU_MU_STATUS
 ,CU_LINE_DISC
 ,CU_TOT_DISC
 ,CU_SETT_DISC_1
 ,CU_SETT_DISC_2
 ,CU_SETT_DAYS_1
 ,CU_SETT_DAYS_2
 ,CU_TERMS_OPTION
 ,CU_CREDIT_LIMIT
 ,CU_TERMS
 ,CU_DEL_CHARGE
 ,CU_DEL_CHARGE_C
 ,CU_DEL_CHG_PCNT
 ,CU_MIN_ORDR
 ,CU_MIN_ORDR_C
 ,CU_DUE_DAYS
 ,CU_A_P_DAYS
 ,CU_ANALYSIS
 ,CU_TAX_CODE
 ,CU_BANK_ANALYS
 ,CU_PRIMARY
 ,CU_DEALERCODE
 ,CU_ADDRESS_USER1
 ,CU_ADDRESS_USER2
 ,CU_EMAIL
 ,CU_WEB_PASSWORD
 ,CU_SOURCE
 ,CU_ACCOUNT_TYPE
 ,CU_DOC_DESTINATION
 ,CU_COUNTRY
 ,CU_DO_NOT_USE
 ,CU_CREDIT_CONTROLLER
 ,CU_TERMS_LINK
 ,CU_CURR_CREDIT_LIMIT
 ,CU_PAYMENT_PROMISED
 ,CU_PAYMENT_PROMISED_DATE
 ,CU_CUSTOM_TERMS_TEMPLATE
 ,CU_PAYMENT_PROMISED_CURRENCY
 ,CU_COMPANY_REG_NUMBER
 ,CU_DIRECT_DEBIT_TYPE
 ,CU_INV_LAYOUT_LINK
 ,CU_CRN_LAYOUT_LINK
 ,CU_COMMITTED_ORDER_TOTAL
 ,CU_COMMITTED_ORDER_TOTAL_C
 ,CU_BIC_CODE
 ,CU_AUDDIS_DATE
 ,CU_DIRECT_DEBIT_STATUS
 ,CU_BUYING_GROUP_FLAG
 ,CU_DIRECT_DEBIT_MANDATE_ID
 ,CU_DIRECT_DEBIT_SIGNATURE_DATE
 ,CU_DD_COLLECTION_ELAPSED_DAYS
 ,CU_DO_NOT_EMAIL_FROM_ACLOUD
)
VALUES
(
  '' -- CUCODE - VARCHAR(10)
 ,'' -- CUNAME - VARCHAR(40)
 ,'' -- CUADDRESS - VARCHAR(160)
 ,'' -- CUPOSTCODE - VARCHAR(12)
 ,'' -- CUPHONE - VARCHAR(20)
 ,'' -- CUPHONE2 - VARCHAR(20)
 ,'' -- CUFAX - VARCHAR(20)
 ,'' -- CUPROSCODE - VARCHAR(10)
 ,'' -- CUCONTACT - VARCHAR(30)
 ,'' -- CUSALUTE - VARCHAR(20)
 ,NOW() -- CU_PRO_CONDATE - DATETIME
 ,'' -- CU_EXPORT_CODE - VARCHAR(1)
 ,'' -- CU_COUNTRY_CODE - VARCHAR(4)
 ,'' -- CU_VAT_REG_NO - VARCHAR(21)
 ,'' -- CU_EC_DELIVERY - VARCHAR(3)
 ,'' -- CU_EC_T_NATURE - VARCHAR(2)
 ,'' -- CU_EC_T_MODE - VARCHAR(1)
 ,0 -- CUBALANCE - DOUBLE
 ,0 -- CUBALANCE_C - DOUBLE
 ,0 -- CUAGED_1 - DOUBLE
 ,0 -- CUAGED_2 - DOUBLE
 ,0 -- CUAGED_3 - DOUBLE
 ,0 -- CUAGED_4 - DOUBLE
 ,0 -- CUAGED_UNALLOC - DOUBLE
 ,'' -- CUSORT - VARCHAR(20)
 ,'' -- CUUSER1 - VARCHAR(20)
 ,'' -- CUUSER2 - VARCHAR(20)
 ,'' -- CUUSER3 - VARCHAR(20)
 ,0 -- CUTURNOVERPTD - DOUBLE
 ,0 -- CUTURNOVR_L1 - DOUBLE
 ,0 -- CUTURNOVR_L2 - DOUBLE
 ,0 -- CUTURNOVR_L3 - DOUBLE
 ,0 -- CUTURNOVR_L4 - DOUBLE
 ,0 -- CUTURNOVR_L5 - DOUBLE
 ,0 -- CUTURNOVR_L6 - DOUBLE
 ,0 -- CUTURNOVR_L7 - DOUBLE
 ,0 -- CUTURNOVR_L8 - DOUBLE
 ,0 -- CUTURNOVR_L9 - DOUBLE
 ,0 -- CUTURNOVR_L10 - DOUBLE
 ,0 -- CUTURNOVR_L11 - DOUBLE
 ,0 -- CUTURNOVR_L12 - DOUBLE
 ,0 -- CUTURNOVR_L13 - DOUBLE
 ,0 -- CUTURNOVR_C1 - DOUBLE
 ,0 -- CUTURNOVR_C2 - DOUBLE
 ,0 -- CUTURNOVR_C3 - DOUBLE
 ,0 -- CUTURNOVR_C4 - DOUBLE
 ,0 -- CUTURNOVR_C5 - DOUBLE
 ,0 -- CUTURNOVR_C6 - DOUBLE
 ,0 -- CUTURNOVR_C7 - DOUBLE
 ,0 -- CUTURNOVR_C8 - DOUBLE
 ,0 -- CUTURNOVR_C9 - DOUBLE
 ,0 -- CUTURNOVR_C10 - DOUBLE
 ,0 -- CUTURNOVR_C11 - DOUBLE
 ,0 -- CUTURNOVR_C12 - DOUBLE
 ,0 -- CUTURNOVR_C13 - DOUBLE
 ,0 -- CUTURNOVR_O1 - DOUBLE
 ,0 -- CUTURNOVR_O2 - DOUBLE
 ,0 -- CUTURNOVR_O3 - DOUBLE
 ,0 -- CUTURNOVR_O4 - DOUBLE
 ,0 -- CUTURNOVR_O5 - DOUBLE
 ,0 -- CUTURNOVR_O6 - DOUBLE
 ,0 -- CUTURNOVR_O7 - DOUBLE
 ,0 -- CUTURNOVR_O8 - DOUBLE
 ,0 -- CUTURNOVR_O9 - DOUBLE
 ,0 -- CUTURNOVR_O10 - DOUBLE
 ,0 -- CUTURNOVR_O11 - DOUBLE
 ,0 -- CUTURNOVR_O12 - DOUBLE
 ,0 -- CUTURNOVR_O13 - DOUBLE
 ,0 -- CUTURNOVERYTD - DOUBLE
 ,'' -- CUCURRENCYCODE - VARCHAR(6)
 ,0 -- CUTURNOVR_L1_C - DOUBLE
 ,0 -- CUTURNOVR_L2_C - DOUBLE
 ,0 -- CUTURNOVR_L3_C - DOUBLE
 ,0 -- CUTURNOVR_L4_C - DOUBLE
 ,0 -- CUTURNOVR_L5_C - DOUBLE
 ,0 -- CUTURNOVR_L6_C - DOUBLE
 ,0 -- CUTURNOVR_L7_C - DOUBLE
 ,0 -- CUTURNOVR_L8_C - DOUBLE
 ,0 -- CUTURNOVR_L9_C - DOUBLE
 ,0 -- CUTURNOVR_L10_C - DOUBLE
 ,0 -- CUTURNOVR_L11_C - DOUBLE
 ,0 -- CUTURNOVR_L12_C - DOUBLE
 ,0 -- CUTURNOVR_L13_C - DOUBLE
 ,0 -- CUTURNOVR_C1_C - DOUBLE
 ,0 -- CUTURNOVR_C2_C - DOUBLE
 ,0 -- CUTURNOVR_C3_C - DOUBLE
 ,0 -- CUTURNOVR_C4_C - DOUBLE
 ,0 -- CUTURNOVR_C5_C - DOUBLE
 ,0 -- CUTURNOVR_C6_C - DOUBLE
 ,0 -- CUTURNOVR_C7_C - DOUBLE
 ,0 -- CUTURNOVR_C8_C - DOUBLE
 ,0 -- CUTURNOVR_C9_C - DOUBLE
 ,0 -- CUTURNOVR_C10_C - DOUBLE
 ,0 -- CUTURNOVR_C11_C - DOUBLE
 ,0 -- CUTURNOVR_C12_C - DOUBLE
 ,0 -- CUTURNOVR_C13_C - DOUBLE
 ,0 -- CUTURNOVR_O1_C - DOUBLE
 ,0 -- CUTURNOVR_O2_C - DOUBLE
 ,0 -- CUTURNOVR_O3_C - DOUBLE
 ,0 -- CUTURNOVR_O4_C - DOUBLE
 ,0 -- CUTURNOVR_O5_C - DOUBLE
 ,0 -- CUTURNOVR_O6_C - DOUBLE
 ,0 -- CUTURNOVR_O7_C - DOUBLE
 ,0 -- CUTURNOVR_O8_C - DOUBLE
 ,0 -- CUTURNOVR_O9_C - DOUBLE
 ,0 -- CUTURNOVR_O10_C - DOUBLE
 ,0 -- CUTURNOVR_O11_C - DOUBLE
 ,0 -- CUTURNOVR_O12_C - DOUBLE
 ,0 -- CUTURNOVR_O13_C - DOUBLE
 ,0 -- CUTURNOVR_YTD_C - DOUBLE
 ,0 -- CUTURNOVR_PTD_C - DOUBLE
 ,0 -- CU_COSTVAL_1 - DOUBLE
 ,0 -- CU_COSTVAL_2 - DOUBLE
 ,0 -- CU_COSTVAL_3 - DOUBLE
 ,0 -- CU_COSTVAL_4 - DOUBLE
 ,0 -- CU_COSTVAL_5 - DOUBLE
 ,0 -- CU_COSTVAL_6 - DOUBLE
 ,0 -- CU_COSTVAL_7 - DOUBLE
 ,0 -- CU_COSTVAL_8 - DOUBLE
 ,0 -- CU_COSTVAL_9 - DOUBLE
 ,0 -- CU_COSTVAL_10 - DOUBLE
 ,0 -- CU_COSTVAL_11 - DOUBLE
 ,0 -- CU_COSTVAL_12 - DOUBLE
 ,0 -- CU_COSTVAL_13 - DOUBLE
 ,0 -- CU_SALEVAL_1 - DOUBLE
 ,0 -- CU_SALEVAL_2 - DOUBLE
 ,0 -- CU_SALEVAL_3 - DOUBLE
 ,0 -- CU_SALEVAL_4 - DOUBLE
 ,0 -- CU_SALEVAL_5 - DOUBLE
 ,0 -- CU_SALEVAL_6 - DOUBLE
 ,0 -- CU_SALEVAL_7 - DOUBLE
 ,0 -- CU_SALEVAL_8 - DOUBLE
 ,0 -- CU_SALEVAL_9 - DOUBLE
 ,0 -- CU_SALEVAL_10 - DOUBLE
 ,0 -- CU_COSTVAL_PTD - DOUBLE
 ,0 -- CU_COSTVAL_YTD - DOUBLE
 ,0 -- CU_SALEVAL_PTD - DOUBLE
 ,0 -- CU_SALEVAL_YTD - DOUBLE
 ,0 -- CU_COSTVALUE - DOUBLE
 ,0 -- CU_SALEVALUE - DOUBLE
 ,0 -- CU_SALEVAL_11 - DOUBLE
 ,0 -- CU_SALEVAL_12 - DOUBLE
 ,0 -- CU_SALEVAL_13 - DOUBLE
 ,NOW() -- CU_USERDATE1 - DATETIME
 ,NOW() -- CU_USERDATE2 - DATETIME
 ,'' -- CU_NOTES - TEXT
 ,0 -- CU_INV_ADD_CDE - DOUBLE
 ,0 -- CU_DEL_ADD_CDE - DOUBLE
 ,0 -- CU_STAT_ADD_CDE - DOUBLE
 ,NOW() -- CU_DATE_INV - DATETIME
 ,NOW() -- CU_DATE_PAY - DATETIME
 ,'' -- CU_USER_PUTIN - VARCHAR(4)
 ,NOW() -- CU_DATE_PUTIN - DATETIME
 ,NOW() -- CU_DATE_EDITED - DATETIME
 ,'' -- CU_USER_EDITED - VARCHAR(4)
 ,'' -- CU_MU_STATUS - VARCHAR(1)
 ,0 -- CU_LINE_DISC - DOUBLE
 ,0 -- CU_TOT_DISC - DOUBLE
 ,0 -- CU_SETT_DISC_1 - DOUBLE
 ,0 -- CU_SETT_DISC_2 - DOUBLE
 ,0 -- CU_SETT_DAYS_1 - DOUBLE
 ,0 -- CU_SETT_DAYS_2 - DOUBLE
 ,0 -- CU_TERMS_OPTION - DOUBLE
 ,0 -- CU_CREDIT_LIMIT - DOUBLE
 ,'' -- CU_TERMS - VARCHAR(40)
 ,0 -- CU_DEL_CHARGE - DOUBLE
 ,0 -- CU_DEL_CHARGE_C - DOUBLE
 ,0 -- CU_DEL_CHG_PCNT - DOUBLE
 ,0 -- CU_MIN_ORDR - DOUBLE
 ,0 -- CU_MIN_ORDR_C - DOUBLE
 ,0 -- CU_DUE_DAYS - DOUBLE
 ,0 -- CU_A_P_DAYS - DOUBLE
 ,'' -- CU_ANALYSIS - VARCHAR(25)
 ,'' -- CU_TAX_CODE - VARCHAR(4)
 ,'' -- CU_BANK_ANALYS - VARCHAR(25)
 ,0 -- CU_PRIMARY - DOUBLE NOT NULL
 ,'' -- CU_DEALERCODE - VARCHAR(10)
 ,'' -- CU_ADDRESS_USER1 - VARCHAR(30)
 ,'' -- CU_ADDRESS_USER2 - VARCHAR(30)
 ,'' -- CU_EMAIL - VARCHAR(64)
 ,'' -- CU_WEB_PASSWORD - VARCHAR(10)
 ,'' -- CU_SOURCE - VARCHAR(1)
 ,'' -- CU_ACCOUNT_TYPE - VARCHAR(1)
 ,'' -- CU_DOC_DESTINATION - VARCHAR(10)
 ,'' -- CU_COUNTRY - VARCHAR(35)
 ,0 -- CU_DO_NOT_USE - TINYINT(4) NOT NULL
 ,'' -- CU_CREDIT_CONTROLLER - VARCHAR(4)
 ,0 -- CU_TERMS_LINK - INT(11)
 ,0 -- CU_CURR_CREDIT_LIMIT - DOUBLE
 ,0 -- CU_PAYMENT_PROMISED - DOUBLE
 ,NOW() -- CU_PAYMENT_PROMISED_DATE - DATETIME
 ,0 -- CU_CUSTOM_TERMS_TEMPLATE - TINYINT(4) NOT NULL
 ,'' -- CU_PAYMENT_PROMISED_CURRENCY - VARCHAR(4)
 ,'' -- CU_COMPANY_REG_NUMBER - VARCHAR(20)
 ,'' -- CU_DIRECT_DEBIT_TYPE - VARCHAR(1) NOT NULL
 ,0 -- CU_INV_LAYOUT_LINK - INT(11)
 ,0 -- CU_CRN_LAYOUT_LINK - INT(11)
 ,0 -- CU_COMMITTED_ORDER_TOTAL - DOUBLE NOT NULL
 ,0 -- CU_COMMITTED_ORDER_TOTAL_C - DOUBLE NOT NULL
 ,'' -- CU_BIC_CODE - VARCHAR(11)
 ,NOW() -- CU_AUDDIS_DATE - DATETIME
 ,'' -- CU_DIRECT_DEBIT_STATUS - VARCHAR(2) NOT NULL
 ,0 -- CU_BUYING_GROUP_FLAG - TINYINT(4) NOT NULL
 ,'' -- CU_DIRECT_DEBIT_MANDATE_ID - VARCHAR(35)
 ,NOW() -- CU_DIRECT_DEBIT_SIGNATURE_DATE - DATETIME
 ,0 -- CU_DD_COLLECTION_ELAPSED_DAYS - TINYINT(4) NOT NULL
 ,0 -- CU_DO_NOT_EMAIL_FROM_ACLOUD - TINYINT(4) NOT NULL
)