INSERT INTO sjbrett_AdvAcct.SL_PL_NL_DETAIL
(
  DET_NETT
 ,DET_VAT
 ,DET_VATCODE
 ,DET_GROSS
 ,DET_UNALLOCATED
 ,DET_BATCH_FLAG
 ,DET_RECUR_FLAG
 ,DET_BATCH_REF
 ,DET_ARCHIVE_FLG
 ,DET_ORIGIN
 ,DET_LEDGER
 ,DET_TYPE
 ,DET_DESCRIPTION
 ,DET_HEADER_REF
 ,DET_JNL_LINEREF
 ,DET_PL_INTERNAL
 ,DET_DATE
 ,DET_TAX_SORT
 ,DET_CURR_TAX
 ,DET_TAX_WITHHLD
 ,DET_PL_ACQ_TAX
 ,DET_CURR_CODE
 ,DET_CURR_RATE
 ,DET_CURR_NETT
 ,DET_CURR_RTEFLG
 ,DET_CURR_UNALOC
 ,DET_CURR_L_DISC
 ,DET_CURR_T_DISC
 ,DET_IMPEXP_CODE
 ,DET_COUNTRY_CDE
 ,DET_ECVAT_TYPE
 ,DET_L_DISCOUNT
 ,DET_T_DISCOUNT
 ,DET_COSTPRICE
 ,DET_PERIOD_SORT
 ,DET_PERIODNUMBR
 ,DET_YEAR
 ,DET_RECONCILED
 ,DET_NOM_PERIOD
 ,DET_NOM_YEAR
 ,DET_NOM_PERSORT
 ,DET_RECON_REF
 ,DT_RECON_ORDER
 ,DET_UNIT_PRICE
 ,DET_QUANTITY
 ,DET_UNT_PRICE_C
 ,DET_UNIT_QTY
 ,DET_USER_PUTIN
 ,DET_DATE_PUTIN
 ,DET_HEADER_KEY
 ,DET_BATCH_POSTD
 ,DET_SERIALNO
 ,DET_STKSORTKEY1
 ,DET_PRICE_CODE
 ,DET_NOMINALDR
 ,DET_NOMINALCR
 ,DET_NOMINALVAT
 ,DET_STOCK_CODE
 ,DET_ACCOUNT
 ,DET_ANALYSIS
 ,DET_COSTHEADER
 ,DET_COSTCENTRE
 ,DET_ANALTYPE
 ,DET_PRIMARY
 ,DET_EC_T_NATURE
 ,DET_SUB_AUDIT_NO
 ,DET_SUB_LEDGER
 ,DET_VAT_RULES
 ,DET_VATNONDEDUCT
 ,DET_STKSORTKEY2
 ,DET_STKSORTKEY3
 ,DET_STKSORTKEY
 ,DET_LANDED_COST
 ,DET_DIMENSION1
 ,DET_DIMENSION2
 ,DET_DIMENSION3
 ,DET_CHEQUE_PAYEE
 ,DET_NETT_BASE2
 ,DET_VAT_BASE2
 ,DET_GROSS_BASE2
 ,DET_L_DISC_BASE2
 ,DET_T_DISC_BASE2
 ,DET_BASE2_RATE
 ,DET_TRI_RATE1
 ,DET_BASE2_RATECHNG
 ,DET_TRI_RATECHNG1
 ,DET_COSTPRICE_BASE2
 ,DET_UNIT_PRICE_BASE2
 ,DET_TAX_WITHHLD_BASE2
 ,DET_PL_ACQUISTN_BASE2
 ,DET_CURR_GROSS
 ,DET_TRI_RATE2
 ,DET_TRI_RATECHNG2
 ,DET_NLCONTRA
 ,DET_HEADER_REF2
 ,DET_SLPL_PRIMARY
 ,DET_SRV_STATUS
 ,DET_ORDER_LINK
 ,DET_SOURCE
 ,DET_VAT_RETURN_PRIMARY
 ,DET_DELIVERY_ADDRESS
 ,DET_POSTING_NO
 ,DET_REVERSE_STATUS
 ,DET_MOVEMENT_LINK
 ,DET_NOM_YEAR_LINK
 ,DET_VAT_RATE
)
VALUES
(
  0 -- DET_NETT - DOUBLE
 ,0 -- DET_VAT - DOUBLE
 ,'' -- DET_VATCODE - VARCHAR(4)
 ,0 -- DET_GROSS - DOUBLE
 ,0 -- DET_UNALLOCATED - DOUBLE
 ,0 -- DET_BATCH_FLAG - TINYINT(4)
 ,0 -- DET_RECUR_FLAG - TINYINT(4)
 ,'' -- DET_BATCH_REF - VARCHAR(10)
 ,0 -- DET_ARCHIVE_FLG - TINYINT(4)
 ,'' -- DET_ORIGIN - VARCHAR(3)
 ,'' -- DET_LEDGER - VARCHAR(2)
 ,'' -- DET_TYPE - VARCHAR(3)
 ,'' -- DET_DESCRIPTION - VARCHAR(240)
 ,'' -- DET_HEADER_REF - VARCHAR(26)
 ,'' -- DET_JNL_LINEREF - VARCHAR(10)
 ,0 -- DET_PL_INTERNAL - DOUBLE
 ,NOW() -- DET_DATE - DATETIME
 ,'' -- DET_TAX_SORT - VARCHAR(4)
 ,0 -- DET_CURR_TAX - DOUBLE
 ,0 -- DET_TAX_WITHHLD - DOUBLE
 ,0 -- DET_PL_ACQ_TAX - DOUBLE
 ,'' -- DET_CURR_CODE - VARCHAR(4)
 ,0 -- DET_CURR_RATE - DOUBLE
 ,0 -- DET_CURR_NETT - DOUBLE
 ,0 -- DET_CURR_RTEFLG - TINYINT(4)
 ,0 -- DET_CURR_UNALOC - DOUBLE
 ,0 -- DET_CURR_L_DISC - DOUBLE
 ,0 -- DET_CURR_T_DISC - DOUBLE
 ,'' -- DET_IMPEXP_CODE - VARCHAR(1)
 ,'' -- DET_COUNTRY_CDE - VARCHAR(4)
 ,'' -- DET_ECVAT_TYPE - VARCHAR(1)
 ,0 -- DET_L_DISCOUNT - DOUBLE
 ,0 -- DET_T_DISCOUNT - DOUBLE
 ,0 -- DET_COSTPRICE - DOUBLE
 ,0 -- DET_PERIOD_SORT - INT(11)
 ,0 -- DET_PERIODNUMBR - TINYINT(4)
 ,'' -- DET_YEAR - VARCHAR(1)
 ,0 -- DET_RECONCILED - TINYINT(4)
 ,0 -- DET_NOM_PERIOD - TINYINT(4)
 ,'' -- DET_NOM_YEAR - VARCHAR(1)
 ,0 -- DET_NOM_PERSORT - INT(11)
 ,'' -- DET_RECON_REF - VARCHAR(10)
 ,0 -- DT_RECON_ORDER - DOUBLE
 ,0 -- DET_UNIT_PRICE - DOUBLE
 ,0 -- DET_QUANTITY - DOUBLE
 ,0 -- DET_UNT_PRICE_C - DOUBLE
 ,0 -- DET_UNIT_QTY - DOUBLE
 ,'' -- DET_USER_PUTIN - VARCHAR(4)
 ,NOW() -- DET_DATE_PUTIN - DATETIME
 ,'' -- DET_HEADER_KEY - VARCHAR(20)
 ,0 -- DET_BATCH_POSTD - TINYINT(4)
 ,'' -- DET_SERIALNO - VARCHAR(40)
 ,'' -- DET_STKSORTKEY1 - VARCHAR(20)
 ,'' -- DET_PRICE_CODE - VARCHAR(16)
 ,'' -- DET_NOMINALDR - VARCHAR(25)
 ,'' -- DET_NOMINALCR - VARCHAR(25)
 ,'' -- DET_NOMINALVAT - VARCHAR(25)
 ,'' -- DET_STOCK_CODE - VARCHAR(25)
 ,'' -- DET_ACCOUNT - VARCHAR(10)
 ,'' -- DET_ANALYSIS - VARCHAR(25)
 ,'' -- DET_COSTHEADER - VARCHAR(10)
 ,'' -- DET_COSTCENTRE - VARCHAR(10)
 ,'' -- DET_ANALTYPE - VARCHAR(1)
 ,0 -- DET_PRIMARY - DOUBLE NOT NULL
 ,'' -- DET_EC_T_NATURE - VARCHAR(2)
 ,0 -- DET_SUB_AUDIT_NO - DOUBLE
 ,'' -- DET_SUB_LEDGER - VARCHAR(10)
 ,0 -- DET_VAT_RULES - TINYINT(4)
 ,0 -- DET_VATNONDEDUCT - DOUBLE
 ,'' -- DET_STKSORTKEY2 - VARCHAR(20)
 ,'' -- DET_STKSORTKEY3 - VARCHAR(20)
 ,'' -- DET_STKSORTKEY - VARCHAR(20)
 ,'' -- DET_LANDED_COST - VARCHAR(1)
 ,'' -- DET_DIMENSION1 - VARCHAR(20)
 ,'' -- DET_DIMENSION2 - VARCHAR(20)
 ,'' -- DET_DIMENSION3 - VARCHAR(20)
 ,'' -- DET_CHEQUE_PAYEE - VARCHAR(40)
 ,0 -- DET_NETT_BASE2 - DOUBLE
 ,0 -- DET_VAT_BASE2 - DOUBLE
 ,0 -- DET_GROSS_BASE2 - DOUBLE
 ,0 -- DET_L_DISC_BASE2 - DOUBLE
 ,0 -- DET_T_DISC_BASE2 - DOUBLE
 ,0 -- DET_BASE2_RATE - DOUBLE
 ,0 -- DET_TRI_RATE1 - DOUBLE
 ,0 -- DET_BASE2_RATECHNG - TINYINT(4)
 ,0 -- DET_TRI_RATECHNG1 - TINYINT(4)
 ,0 -- DET_COSTPRICE_BASE2 - DOUBLE
 ,0 -- DET_UNIT_PRICE_BASE2 - DOUBLE
 ,0 -- DET_TAX_WITHHLD_BASE2 - DOUBLE
 ,0 -- DET_PL_ACQUISTN_BASE2 - DOUBLE
 ,0 -- DET_CURR_GROSS - DOUBLE
 ,0 -- DET_TRI_RATE2 - DOUBLE
 ,0 -- DET_TRI_RATECHNG2 - TINYINT(4)
 ,'' -- DET_NLCONTRA - VARCHAR(25)
 ,'' -- DET_HEADER_REF2 - VARCHAR(10)
 ,'' -- DET_SLPL_PRIMARY - VARCHAR(20)
 ,0 -- DET_SRV_STATUS - TINYINT(4)
 ,0 -- DET_ORDER_LINK - INT(11)
 ,'' -- DET_SOURCE - VARCHAR(1)
 ,0 -- DET_VAT_RETURN_PRIMARY - INT(11)
 ,'' -- DET_DELIVERY_ADDRESS - VARCHAR(16)
 ,0 -- DET_POSTING_NO - INT(11)
 ,0 -- DET_REVERSE_STATUS - TINYINT(4)
 ,0 -- DET_MOVEMENT_LINK - INT(11)
 ,0 -- DET_NOM_YEAR_LINK - INT(11)
 ,0 -- DET_VAT_RATE - DOUBLE
)