INSERT INTO sjbrett_AdvAcct.SL_TRANSACTIONS
(
  ST_TRANTYPE
 ,ST_HEADER_REF
 ,ST_DESCRIPTION
 ,ST_DATE
 ,ST_DUEDATE
 ,ST_ANTICPAYDATE
 ,ST_SETT_DISC_1
 ,ST_SETT_DISC_2
 ,ST_SETT_DAYS_1
 ,ST_SETT_DAYS_2
 ,ST_NETT
 ,ST_VAT
 ,ST_GROSS
 ,ST_UNALLOCATED
 ,ST_BATCH_FLAG
 ,ST_BATCH_REF
 ,ST_ARCHIVE_FLAG
 ,ST_ALOC_POINTER
 ,ST_ORIGIN
 ,ST_REVALUE_RATE
 ,ST_CURRENCYRATE
 ,ST_CURRENCYCODE
 ,ST_CURR_VALU
 ,ST_CURR_UNAL
 ,ST_CURRENCYRTCH
 ,ST_CURRENCYEXDF
 ,ST_EXPORT_CODE
 ,ST_EC_DEL_TERMS
 ,ST_EC_T_NATURE
 ,ST_EC_T_MODE
 ,ST_REVALUED
 ,ST_REVALUE_DATE
 ,ST_QUERY_FLAG
 ,ST_DONOTCHASE
 ,ST_CHASE1
 ,ST_CHASE2
 ,ST_CHASE3
 ,ST_PERIODNUMBER
 ,ST_YEAR
 ,ST_ALLOC_USER1
 ,ST_ALLOC_USER2
 ,ST_ALLOC_USER3
 ,ST_ALLOC_DATE1
 ,ST_ALLOC_DATE2
 ,ST_ALLOC_DATE3
 ,ST_ALLOC_VALU1
 ,ST_ALLOC_VALU2
 ,ST_ALLOC_VALU3
 ,ST_ALLOC_REF1
 ,ST_ALLOC_REF2
 ,ST_ALLOC_REF3
 ,ST_ALLOC_PERIOD
 ,ST_ALLOC_YEAR
 ,ST_T_DISCVAL
 ,ST_T_DISCVAL_C
 ,ST_L_DISCVAL
 ,ST_L_DISCVAL_C
 ,ST_COST_VALUE
 ,ST_USER_PUTIN
 ,ST_DATE_PUTIN
 ,ST_MU_STATUS
 ,ST_USER1
 ,ST_USER2
 ,ST_USER3
 ,ST_BATCH_POSTED
 ,ST_PRINTED_FLAG
 ,ST_CON_REFTYPE
 ,ST_ORDER_NUMBER
 ,ST_COPYCUST
 ,ST_REBUILDNUM
 ,ST_PRIMARY
 ,ST_HEADER_KEY
 ,ST_SUB_LEDGER
 ,ST_ALLOC_CBREF
 ,ST_CENTRALISED
 ,ST_RECONCILED
 ,ST_ALLOC_XREF
 ,ST_NETT_BASE2
 ,ST_VAT_BASE2
 ,ST_GROSS_BASE2
 ,ST_L_DISC_BASE2
 ,ST_T_DISC_BASE2
 ,ST_BASE2_RATE
 ,ST_TRI_RATE1
 ,ST_BASE2_RATECHNG
 ,ST_TRI_RATECHNG1
 ,ST_RND_DIFF_BASE1
 ,ST_COSTVALUE_BASE2
 ,ST_CURR_NETT
 ,ST_CURR_TAX
 ,ST_CURR_TYPE
 ,ST_TRI_RATE2
 ,ST_TRI_RATECHNG2
 ,ST_RND_DIFF_POSTED
 ,ST_SPCL_TRANTYPE
 ,ST_SRV_STATUS
 ,ST_RND_DIFF_BASE2
 ,ST_SOURCE
 ,ST_TRAN_OPTIONS
 ,ST_REVERSE_VAT
 ,ST_REVERSE_VAT_BASE2
 ,ST_DEBT_STATUS_LINK
 ,ST_CREDIT_CONTROLLER
 ,ST_WRITE_OFF_STATUS
 ,ST_NOM_CAT_LINK
 ,ST_YEAR_LINK
 ,ST_ALLOC_YEAR_LINK
 ,ST_WFF_APPROVAL_STATUS
 ,ST_DD_COLLECTION_STATUS
 ,ST_QUERIED_IN_ACLOUD
)
VALUES
(
  '' -- ST_TRANTYPE - VARCHAR(3)
 ,'' -- ST_HEADER_REF - VARCHAR(10)
 ,'' -- ST_DESCRIPTION - VARCHAR(30)
 ,NOW() -- ST_DATE - DATETIME
 ,NOW() -- ST_DUEDATE - DATETIME
 ,NOW() -- ST_ANTICPAYDATE - DATETIME
 ,0 -- ST_SETT_DISC_1 - DOUBLE
 ,0 -- ST_SETT_DISC_2 - DOUBLE
 ,0 -- ST_SETT_DAYS_1 - DOUBLE
 ,0 -- ST_SETT_DAYS_2 - DOUBLE
 ,0 -- ST_NETT - DOUBLE
 ,0 -- ST_VAT - DOUBLE
 ,0 -- ST_GROSS - DOUBLE
 ,0 -- ST_UNALLOCATED - DOUBLE
 ,0 -- ST_BATCH_FLAG - TINYINT(4)
 ,'' -- ST_BATCH_REF - VARCHAR(10)
 ,0 -- ST_ARCHIVE_FLAG - TINYINT(4)
 ,'' -- ST_ALOC_POINTER - VARCHAR(11)
 ,'' -- ST_ORIGIN - VARCHAR(2)
 ,0 -- ST_REVALUE_RATE - DOUBLE
 ,0 -- ST_CURRENCYRATE - DOUBLE
 ,'' -- ST_CURRENCYCODE - VARCHAR(4)
 ,0 -- ST_CURR_VALU - DOUBLE
 ,0 -- ST_CURR_UNAL - DOUBLE
 ,0 -- ST_CURRENCYRTCH - TINYINT(4)
 ,0 -- ST_CURRENCYEXDF - DOUBLE
 ,'' -- ST_EXPORT_CODE - VARCHAR(1)
 ,'' -- ST_EC_DEL_TERMS - VARCHAR(3)
 ,'' -- ST_EC_T_NATURE - VARCHAR(2)
 ,'' -- ST_EC_T_MODE - VARCHAR(1)
 ,0 -- ST_REVALUED - DOUBLE
 ,NOW() -- ST_REVALUE_DATE - DATETIME
 ,0 -- ST_QUERY_FLAG - TINYINT(4)
 ,0 -- ST_DONOTCHASE - TINYINT(4)
 ,0 -- ST_CHASE1 - TINYINT(4)
 ,0 -- ST_CHASE2 - TINYINT(4)
 ,0 -- ST_CHASE3 - TINYINT(4)
 ,0 -- ST_PERIODNUMBER - TINYINT(4)
 ,'' -- ST_YEAR - VARCHAR(1)
 ,'' -- ST_ALLOC_USER1 - VARCHAR(4)
 ,'' -- ST_ALLOC_USER2 - VARCHAR(4)
 ,'' -- ST_ALLOC_USER3 - VARCHAR(4)
 ,NOW() -- ST_ALLOC_DATE1 - DATETIME
 ,NOW() -- ST_ALLOC_DATE2 - DATETIME
 ,NOW() -- ST_ALLOC_DATE3 - DATETIME
 ,0 -- ST_ALLOC_VALU1 - DOUBLE
 ,0 -- ST_ALLOC_VALU2 - DOUBLE
 ,0 -- ST_ALLOC_VALU3 - DOUBLE
 ,'' -- ST_ALLOC_REF1 - VARCHAR(10)
 ,'' -- ST_ALLOC_REF2 - VARCHAR(10)
 ,'' -- ST_ALLOC_REF3 - VARCHAR(10)
 ,0 -- ST_ALLOC_PERIOD - TINYINT(4)
 ,'' -- ST_ALLOC_YEAR - VARCHAR(1)
 ,0 -- ST_T_DISCVAL - DOUBLE
 ,0 -- ST_T_DISCVAL_C - DOUBLE
 ,0 -- ST_L_DISCVAL - DOUBLE
 ,0 -- ST_L_DISCVAL_C - DOUBLE
 ,0 -- ST_COST_VALUE - DOUBLE
 ,'' -- ST_USER_PUTIN - VARCHAR(4)
 ,NOW() -- ST_DATE_PUTIN - DATETIME
 ,'' -- ST_MU_STATUS - VARCHAR(1)
 ,'' -- ST_USER1 - VARCHAR(20)
 ,'' -- ST_USER2 - VARCHAR(20)
 ,'' -- ST_USER3 - VARCHAR(20)
 ,'' -- ST_BATCH_POSTED - VARCHAR(1)
 ,0 -- ST_PRINTED_FLAG - TINYINT(4)
 ,'' -- ST_CON_REFTYPE - VARCHAR(11)
 ,0 -- ST_ORDER_NUMBER - DOUBLE
 ,'' -- ST_COPYCUST - VARCHAR(10)
 ,0 -- ST_REBUILDNUM - DOUBLE
 ,0 -- ST_PRIMARY - DOUBLE NOT NULL
 ,'' -- ST_HEADER_KEY - VARCHAR(20)
 ,'' -- ST_SUB_LEDGER - VARCHAR(10)
 ,'' -- ST_ALLOC_CBREF - VARCHAR(10)
 ,0 -- ST_CENTRALISED - TINYINT(4)
 ,0 -- ST_RECONCILED - TINYINT(4)
 ,'' -- ST_ALLOC_XREF - VARCHAR(15)
 ,0 -- ST_NETT_BASE2 - DOUBLE
 ,0 -- ST_VAT_BASE2 - DOUBLE
 ,0 -- ST_GROSS_BASE2 - DOUBLE
 ,0 -- ST_L_DISC_BASE2 - DOUBLE
 ,0 -- ST_T_DISC_BASE2 - DOUBLE
 ,0 -- ST_BASE2_RATE - DOUBLE
 ,0 -- ST_TRI_RATE1 - DOUBLE
 ,0 -- ST_BASE2_RATECHNG - TINYINT(4)
 ,0 -- ST_TRI_RATECHNG1 - TINYINT(4)
 ,0 -- ST_RND_DIFF_BASE1 - DOUBLE
 ,0 -- ST_COSTVALUE_BASE2 - DOUBLE
 ,0 -- ST_CURR_NETT - DOUBLE
 ,0 -- ST_CURR_TAX - DOUBLE
 ,'' -- ST_CURR_TYPE - VARCHAR(1)
 ,0 -- ST_TRI_RATE2 - DOUBLE
 ,0 -- ST_TRI_RATECHNG2 - TINYINT(4)
 ,0 -- ST_RND_DIFF_POSTED - TINYINT(4)
 ,'' -- ST_SPCL_TRANTYPE - VARCHAR(20)
 ,0 -- ST_SRV_STATUS - TINYINT(4)
 ,0 -- ST_RND_DIFF_BASE2 - DOUBLE
 ,'' -- ST_SOURCE - VARCHAR(1)
 ,'' -- ST_TRAN_OPTIONS - VARCHAR(30)
 ,0 -- ST_REVERSE_VAT - DOUBLE
 ,0 -- ST_REVERSE_VAT_BASE2 - DOUBLE
 ,0 -- ST_DEBT_STATUS_LINK - INT(11)
 ,'' -- ST_CREDIT_CONTROLLER - VARCHAR(4)
 ,0 -- ST_WRITE_OFF_STATUS - TINYINT(4)
 ,0 -- ST_NOM_CAT_LINK - INT(11)
 ,0 -- ST_YEAR_LINK - INT(11)
 ,0 -- ST_ALLOC_YEAR_LINK - INT(11)
 ,0 -- ST_WFF_APPROVAL_STATUS - INT(11)
 ,'' -- ST_DD_COLLECTION_STATUS - VARCHAR(1)
 ,0 -- ST_QUERIED_IN_ACLOUD - TINYINT(4) NOT NULL
)