UPDATE sjbrett_AdvAcct.NL_CATEGORIES 
SET
  NCAT_PRIMARY = 0 -- NCAT_PRIMARY - INT(11) NOT NULL
 ,NCAT_CODE = '' -- NCAT_CODE - VARCHAR(6) NOT NULL
 ,NCAT_NAME = '' -- NCAT_NAME - VARCHAR(50)
 ,NCAT_SHORTNAME = '' -- NCAT_SHORTNAME - VARCHAR(10)
 ,NCAT_NUMBER = 0 -- NCAT_NUMBER - TINYINT(4) NOT NULL
 ,NCAT_USED = 0 -- NCAT_USED - TINYINT(4) NOT NULL
 ,NCAT_DRCR_TYPE = 0 -- NCAT_DRCR_TYPE - TINYINT(4)
 ,NCAT_MAJOR_HEADING = 0 -- NCAT_MAJOR_HEADING - TINYINT(4)
 ,NCAT_TAXCODE_DR = '' -- NCAT_TAXCODE_DR - VARCHAR(4)
 ,NCAT_TAXCODE_CR = '' -- NCAT_TAXCODE_CR - VARCHAR(4)
 ,NCAT_LEVEL = 0 -- NCAT_LEVEL - INT(11)
 ,NCAT_CURR_SYMBOL = '' -- NCAT_CURR_SYMBOL - VARCHAR(4)
 ,NCAT_BANK_ACCOUNT = 0 -- NCAT_BANK_ACCOUNT - TINYINT(4) NOT NULL
 ,NCAT_PETTY_CASH_ACCOUNT = 0 -- NCAT_PETTY_CASH_ACCOUNT - TINYINT(4) NOT NULL
 ,NCAT_COMPULSORY_COSTING = 0 -- NCAT_COMPULSORY_COSTING - TINYINT(4) NOT NULL
 ,NCAT_ACCOUNT_FOR_CO2 = 0 -- NCAT_ACCOUNT_FOR_CO2 - TINYINT(4) NOT NULL
 ,NCAT_EMISSIONS_GROUP_LINK = 0 -- NCAT_EMISSIONS_GROUP_LINK - INT(11)
 ,NCAT_CLASSIFICATION_LINK = 0 -- NCAT_CLASSIFICATION_LINK - INT(11)
 ,NCAT_INACTIVE = 0 -- NCAT_INACTIVE - TINYINT(4) NOT NULL
 ,NCAT_SORT = '' -- NCAT_SORT - VARCHAR(20)
 ,NCAT_REPORTING_CODE = 0 -- NCAT_REPORTING_CODE - INT(11)
WHERE
<Search Conditions,,>