namespace Advanced_Accounting.Classes.MySQLDataConnectors
{
    public static class MySqlSlAccounts
    {
        public static string Cucode { get; set; }
        public static string Cuname { get; set; }
        public static string Cuaddress { get; set; }
        public static string Cupostcode { get; set; }
        public static string Cuphone { get; set; }
        public static string Cuphone2 { get; set; }
        public static string Cufax { get; set; }
        public static string Cuproscode { get; set; }
        public static string Cucontact { get; set; }
        public static string Cusalute { get; set; }
        public static string CuProCondate { get; set; }
        public static string CuExportCode { get; set; }
        public static string CuCountryCode { get; set; }
        public static string CuVatRegNo { get; set; }
        public static string CuEcDelivery { get; set; }
        public static string CuEcTNature { get; set; }
        public static string CuEcTMode { get; set; }
        public static string Cubalance { get; set; }
        public static string CubalanceC { get; set; }
        public static string Cuaged1 { get; set; }
        public static string Cuaged2 { get; set; }
        public static string Cuaged3 { get; set; }
        public static string Cuaged4 { get; set; }
        public static string CuagedUnalloc { get; set; }
        public static string Cusort { get; set; }
        public static string Cuuser1 { get; set; }
        public static string Cuuser2 { get; set; }
        public static string Cuuser3 { get; set; }
        public static string Cuturnoverptd { get; set; }
        public static string CuturnovrL1 { get; set; }
        public static string CuturnovrL2 { get; set; }
        public static string CuturnovrL3 { get; set; }
        public static string CuturnovrL4 { get; set; }
        public static string CuturnovrL5 { get; set; }
        public static string CuturnovrL6 { get; set; }
        public static string CuturnovrL7 { get; set; }
        public static string CuturnovrL8 { get; set; }
        public static string CuturnovrL9 { get; set; }
        public static string CuturnovrL10 { get; set; }
        public static string CuturnovrL11 { get; set; }
        public static string CuturnovrL12 { get; set; }
        public static string CuturnovrL13 { get; set; }
        public static string CuturnovrC1 { get; set; }
        public static string CuturnovrC2 { get; set; }
        public static string CuturnovrC3 { get; set; }
        public static string CuturnovrC4 { get; set; }
        public static string CuturnovrC5 { get; set; }
        public static string CuturnovrC6 { get; set; }
        public static string CuturnovrC7 { get; set; }
        public static string CuturnovrC8 { get; set; }
        public static string CuturnovrC9 { get; set; }
        public static string CuturnovrC10 { get; set; }
        public static string CuturnovrC11 { get; set; }
        public static string CuturnovrC12 { get; set; }
        public static string CuturnovrC13 { get; set; }
        public static string CuturnovrO1 { get; set; }
        public static string CuturnovrO2 { get; set; }
        public static string CuturnovrO3 { get; set; }
        public static string CuturnovrO4 { get; set; }
        public static string CuturnovrO5 { get; set; }
        public static string CuturnovrO6 { get; set; }
        public static string CuturnovrO7 { get; set; }
        public static string CuturnovrO8 { get; set; }
        public static string CuturnovrO9 { get; set; }
        public static string CuturnovrO10 { get; set; }
        public static string CuturnovrO11 { get; set; }
        public static string CuturnovrO12 { get; set; }
        public static string CuturnovrO13 { get; set; }
        public static string Cuturnoverytd { get; set; }
        public static string Cucurrencycode { get; set; }
        public static string CuturnovrL1C { get; set; }
        public static string CuturnovrL2C { get; set; }
        public static string CuturnovrL3C { get; set; }
        public static string CuturnovrL4C { get; set; }
        public static string CuturnovrL5C { get; set; }
        public static string CuturnovrL6C { get; set; }
        public static string CuturnovrL7C { get; set; }
        public static string CuturnovrL8C { get; set; }
        public static string CuturnovrL9C { get; set; }
        public static string CuturnovrL10C { get; set; }
        public static string CuturnovrL11C { get; set; }
        public static string CuturnovrL12C { get; set; }
        public static string CuturnovrL13C { get; set; }
        public static string CuturnovrC1C { get; set; }
        public static string CuturnovrC2C { get; set; }
        public static string CuturnovrC3C { get; set; }
        public static string CuturnovrC4C { get; set; }
        public static string CuturnovrC5C { get; set; }
        public static string CuturnovrC6C { get; set; }
        public static string CuturnovrC7C { get; set; }
        public static string CuturnovrC8C { get; set; }
        public static string CuturnovrC9C { get; set; }
        public static string CuturnovrC10C { get; set; }
        public static string CuturnovrC11C { get; set; }
        public static string CuturnovrC12C { get; set; }
        public static string CuturnovrC13C { get; set; }
        public static string CuturnovrO1C { get; set; }
        public static string CuturnovrO2C { get; set; }
        public static string CuturnovrO3C { get; set; }
        public static string CuturnovrO4C { get; set; }
        public static string CuturnovrO5C { get; set; }
        public static string CuturnovrO6C { get; set; }
        public static string CuturnovrO7C { get; set; }
        public static string CuturnovrO8C { get; set; }
        public static string CuturnovrO9C { get; set; }
        public static string CuturnovrO10C { get; set; }
        public static string CuturnovrO11C { get; set; }
        public static string CuturnovrO12C { get; set; }
        public static string CuturnovrO13C { get; set; }
        public static string CuturnovrYtdC { get; set; }
        public static string CuturnovrPtdC { get; set; }
        public static string CuCostval1 { get; set; }
        public static string CuCostval2 { get; set; }
        public static string CuCostval3 { get; set; }
        public static string CuCostval4 { get; set; }
        public static string CuCostval5 { get; set; }
        public static string CuCostval6 { get; set; }
        public static string CuCostval7 { get; set; }
        public static string CuCostval8 { get; set; }
        public static string CuCostval9 { get; set; }
        public static string CuCostval10 { get; set; }
        public static string CuCostval11 { get; set; }
        public static string CuCostval12 { get; set; }
        public static string CuCostval13 { get; set; }
        public static string CuSaleval1 { get; set; }
        public static string CuSaleval2 { get; set; }
        public static string CuSaleval3 { get; set; }
        public static string CuSaleval4 { get; set; }
        public static string CuSaleval5 { get; set; }
        public static string CuSaleval6 { get; set; }
        public static string CuSaleval7 { get; set; }
        public static string CuSaleval8 { get; set; }
        public static string CuSaleval9 { get; set; }
        public static string CuSaleval10 { get; set; }
        public static string CuCostvalPtd { get; set; }
        public static string CuCostvalYtd { get; set; }
        public static string CuSalevalPtd { get; set; }
        public static string CuSalevalYtd { get; set; }
        public static string CuCostvalue { get; set; }
        public static string CuSalevalue { get; set; }
        public static string CuSaleval11 { get; set; }
        public static string CuSaleval12 { get; set; }
        public static string CuSaleval13 { get; set; }
        public static string CuUserdate1 { get; set; }
        public static string CuUserdate2 { get; set; }
        public static string CuNotes { get; set; }
        public static string CuInvAddCde { get; set; }
        public static string CuDelAddCde { get; set; }
        public static string CuStatAddCde { get; set; }
        public static string CuDateInv { get; set; }
        public static string CuDatePay { get; set; }
        public static string CuUserPutin { get; set; }
        public static string CuDatePutin { get; set; }
        public static string CuDateEdited { get; set; }
        public static string CuUserEdited { get; set; }
        public static string CuMuStatus { get; set; }
        public static string CuLineDisc { get; set; }
        public static string CuTotDisc { get; set; }
        public static string CuSettDisc1 { get; set; }
        public static string CuSettDisc2 { get; set; }
        public static string CuSettDays1 { get; set; }
        public static string CuSettDays2 { get; set; }
        public static string CuTermsOption { get; set; }
        public static string CuCreditLimit { get; set; }
        public static string CuTerms { get; set; }
        public static string CuDelCharge { get; set; }
        public static string CuDelChargeC { get; set; }
        public static string CuDelChgPcnt { get; set; }
        public static string CuMinOrdr { get; set; }
        public static string CuMinOrdrC { get; set; }
        public static string CuDueDays { get; set; }
        public static string CuAPDays { get; set; }
        public static string CuAnalysis { get; set; }
        public static string CuTaxCode { get; set; }
        public static string CuBankAnalys { get; set; }
        public static string CuPrimary { get; set; }
        public static string CuDealercode { get; set; }
        public static string CuAddressUser1 { get; set; }
        public static string CuAddressUser2 { get; set; }
        public static string CuEmail { get; set; }
        public static string CuWebPassword { get; set; }
        public static string CuSource { get; set; }
        public static string CuAccountType { get; set; }
        public static string CuDocDestination { get; set; }
        public static string CuCountry { get; set; }
        public static string CuDoNotUse { get; set; }
        public static string CuCreditController { get; set; }
        public static string CuTermsLink { get; set; }
        public static string CuCurrCreditLimit { get; set; }
        public static string CuPaymentPromised { get; set; }
        public static string CuPaymentPromisedDate { get; set; }
        public static string CuCustomTermsTemplate { get; set; }
        public static string CuPaymentPromisedCurrency { get; set; }
        public static string CuCompanyRegNumber { get; set; }
        public static string CuDirectDebitType { get; set; }
        public static string CuInvLayoutLink { get; set; }
        public static string CuCrnLayoutLink { get; set; }
        public static string CuCommittedOrderTotal { get; set; }
        public static string CuCommittedOrderTotalC { get; set; }
        public static string CuBicCode { get; set; }
        public static string CuAuddisDate { get; set; }
        public static string CuDirectDebitStatus { get; set; }
        public static string CuBuyingGroupFlag { get; set; }
        public static string CuDirectDebitMandateId { get; set; }
        public static string CuDirectDebitSignatureDate { get; set; }
        public static string CuDdCollectionElapsedDays { get; set; }
        public static string CuDoNotEmailFromAcloud { get; set; }
    }
}
