namespace Advanced_Accounting.Classes.MySQLDataConnectors
{
    public static class MySqlPlTransactions
    {
        public static string PtTrantype { get; set; }
        public static string PtHeaderRef { get; set; }
        public static string PtInternalRef { get; set; }
        public static string PtDescription { get; set; }
        public static string PtDate { get; set; }
        public static string PtDuedate { get; set; }
        public static string PtAnticpaydate { get; set; }
        public static string PtSettDisc1 { get; set; }
        public static string PtSettDisc2 { get; set; }
        public static string PtSettDays1 { get; set; }
        public static string PtSettDays2 { get; set; }
        public static string PtNett { get; set; }
        public static string PtVat { get; set; }
        public static string PtGross { get; set; }
        public static string PtUnallocated { get; set; }
        public static string PtBatchFlag { get; set; }
        public static string PtBatchRef { get; set; }
        public static string PtArchiveFlag { get; set; }
        public static string PtAlocPointer { get; set; }
        public static string PtOrigin { get; set; }
        public static string PtRevalueRate { get; set; }
        public static string PtCurrencyrate { get; set; }
        public static string PtCurrencycode { get; set; }
        public static string PtCurrValu { get; set; }
        public static string PtCurrUnal { get; set; }
        public static string PtCurrencyrtch { get; set; }
        public static string PtCurrencyexdf { get; set; }
        public static string PtAcquistnTax { get; set; }
        public static string PtImportCode { get; set; }
        public static string PtRevalued { get; set; }
        public static string PtEcDelTerms { get; set; }
        public static string PtEcTNature { get; set; }
        public static string PtEcTMode { get; set; }
        public static string PtRevalueDate { get; set; }
        public static string PtPaymentFlag { get; set; }
        public static string PtQueryFlag { get; set; }
        public static string PtDonotchase { get; set; }
        public static string PtChase1 { get; set; }
        public static string PtChase2 { get; set; }
        public static string PtChase3 { get; set; }
        public static string PtPeriodnumber { get; set; }
        public static string PtYear { get; set; }
        public static string PtAllocUser1 { get; set; }
        public static string PtAllocUser2 { get; set; }
        public static string PtAllocUser3 { get; set; }
        public static string PtAllocDate1 { get; set; }
        public static string PtAllocDate2 { get; set; }
        public static string PtAllocDate3 { get; set; }
        public static string PtAllocValu1 { get; set; }
        public static string PtAllocValu2 { get; set; }
        public static string PtAllocValu3 { get; set; }
        public static string PtAllocRef1 { get; set; }
        public static string PtAllocRef2 { get; set; }
        public static string PtAllocRef3 { get; set; }
        public static string PtAllocPeriod { get; set; }
        public static string PtAllocYear { get; set; }
        public static string PtTDiscval { get; set; }
        public static string PtTDiscvalC { get; set; }
        public static string PtLDiscval { get; set; }
        public static string PtLDiscvalC { get; set; }
        public static string PtUserPutin { get; set; }
        public static string PtDatePutin { get; set; }
        public static string PtMuStatus { get; set; }
        public static string PtUser1 { get; set; }
        public static string PtUser2 { get; set; }
        public static string PtUser3 { get; set; }
        public static string PtBatchPosted { get; set; }
        public static string PtConReftype { get; set; }
        public static string PtOrderNumber { get; set; }
        public static string PtCopysupp { get; set; }
        public static string PtRebuildnum { get; set; }
        public static string PtPrimary { get; set; }
        public static string PtHeaderKey { get; set; }
        public static string PtSubLedger { get; set; }
        public static string PtAllocCbref { get; set; }
        public static string PtCentralised { get; set; }
        public static string PtPaylistValue { get; set; }
        public static string PtPaylistSettDisc { get; set; }
        public static string PtPaylistRef { get; set; }
        public static string PtInvregFlag { get; set; }
        public static string PtInvregStatus { get; set; }
        public static string PtInvregType { get; set; }
        public static string PtInvregOveride { get; set; }
        public static string PtInvregApprover1 { get; set; }
        public static string PtInvregApprover2 { get; set; }
        public static string PtInvregApprover3 { get; set; }
        public static string PtInvregApprovekey1 { get; set; }
        public static string PtInvregApprovekey2 { get; set; }
        public static string PtInvregApprovekey3 { get; set; }
        public static string PtInvregApprovedate1 { get; set; }
        public static string PtInvregApprovedate2 { get; set; }
        public static string PtInvregApprovedate3 { get; set; }
        public static string PtInvregMatcheduser { get; set; }
        public static string PtInvregMatcheddate { get; set; }
        public static string PtInvregMatchedkey { get; set; }
        public static string PtInvregApprovestatus { get; set; }
        public static string PtPayStage1User { get; set; }
        public static string PtPayStage2User { get; set; }
        public static string PtPayStageStatus { get; set; }
        public static string PtReconciled { get; set; }
        public static string PtAllocXref { get; set; }
        public static string PtNettBase2 { get; set; }
        public static string PtVatBase2 { get; set; }
        public static string PtGrossBase2 { get; set; }
        public static string PtLDiscBase2 { get; set; }
        public static string PtTDiscBase2 { get; set; }
        public static string PtBase2Rate { get; set; }
        public static string PtTriRate1 { get; set; }
        public static string PtBase2Ratechng { get; set; }
        public static string PtTriRatechng1 { get; set; }
        public static string PtAcquistnBase2 { get; set; }
        public static string PtRndDiffBase1 { get; set; }
        public static string PtCurrNett { get; set; }
        public static string PtCurrTax { get; set; }
        public static string PtCurrType { get; set; }
        public static string PtTriRate2 { get; set; }
        public static string PtTriRatechng2 { get; set; }
        public static string PtRndDiffPosted { get; set; }
        public static string PtSpclTrantype { get; set; }
        public static string PtHeaderRef2 { get; set; }
        public static string PtSrvStatus { get; set; }
        public static string PtRndDiffBase2 { get; set; }
        public static string PtSource { get; set; }
        public static string PtTranOptions { get; set; }
        public static string PtSurveyor { get; set; }
        public static string PtCisSentTo { get; set; }
        public static string PtCisSentDate { get; set; }
        public static string PtCisAuthorised { get; set; }
        public static string PtCisAuthorisedDate { get; set; }
        public static string PtCisPayeeName { get; set; }
        public static string PtCis300Flag { get; set; }
        public static string PtPartner { get; set; }
        public static string PtDateReceived { get; set; }
        public static string PtInvregTranOptions { get; set; }
        public static string PtNomCatLink { get; set; }
        public static string PtYearLink { get; set; }
        public static string PtAllocYearLink { get; set; }
        public static string PtBacsLayout { get; set; }
        public static string PtReverseServiceVat { get; set; }
        public static string PtReverseServiceVatBase2 { get; set; }
        public static string PtWffApprovalStatus { get; set; }
        public static string PtCurrAcquistn { get; set; }
    }
}
