namespace Advanced_Accounting.Classes.MySQLDataConnectors
{
    public static class MySqlSlTransactions
    {
        public static string StTrantype { get; set; }
        public static string StHeaderRef { get; set; }
        public static string StDescription { get; set; }
        public static string StDate { get; set; }
        public static string StDuedate { get; set; }
        public static string StAnticpaydate { get; set; }
        public static string StSettDisc1 { get; set; }
        public static string StSettDisc2 { get; set; }
        public static string StSettDays1 { get; set; }
        public static string StSettDays2 { get; set; }
        public static string StNett { get; set; }
        public static string StVat { get; set; }
        public static string StGross { get; set; }
        public static string StUnallocated { get; set; }
        public static string StBatchFlag { get; set; }
        public static string StBatchRef { get; set; }
        public static string StArchiveFlag { get; set; }
        public static string StAlocPointer { get; set; }
        public static string StOrigin { get; set; }
        public static string StRevalueRate { get; set; }
        public static string StCurrencyrate { get; set; }
        public static string StCurrencycode { get; set; }
        public static string StCurrValu { get; set; }
        public static string StCurrUnal { get; set; }
        public static string StCurrencyrtch { get; set; }
        public static string StCurrencyexdf { get; set; }
        public static string StExportCode { get; set; }
        public static string StEcDelTerms { get; set; }
        public static string StEcTNature { get; set; }
        public static string StEcTMode { get; set; }
        public static string StRevalued { get; set; }
        public static string StRevalueDate { get; set; }
        public static string StQueryFlag { get; set; }
        public static string StDonotchase { get; set; }
        public static string StChase1 { get; set; }
        public static string StChase2 { get; set; }
        public static string StChase3 { get; set; }
        public static string StPeriodnumber { get; set; }
        public static string StYear { get; set; }
        public static string StAllocUser1 { get; set; }
        public static string StAllocUser2 { get; set; }
        public static string StAllocUser3 { get; set; }
        public static string StAllocDate1 { get; set; }
        public static string StAllocDate2 { get; set; }
        public static string StAllocDate3 { get; set; }
        public static string StAllocValu1 { get; set; }
        public static string StAllocValu2 { get; set; }
        public static string StAllocValu3 { get; set; }
        public static string StAllocRef1 { get; set; }
        public static string StAllocRef2 { get; set; }
        public static string StAllocRef3 { get; set; }
        public static string StAllocPeriod { get; set; }
        public static string StAllocYear { get; set; }
        public static string StTDiscval { get; set; }
        public static string StTDiscvalC { get; set; }
        public static string StLDiscval { get; set; }
        public static string StLDiscvalC { get; set; }
        public static string StCostValue { get; set; }
        public static string StUserPutin { get; set; }
        public static string StDatePutin { get; set; }
        public static string StMuStatus { get; set; }
        public static string StUser1 { get; set; }
        public static string StUser2 { get; set; }
        public static string StUser3 { get; set; }
        public static string StBatchPosted { get; set; }
        public static string StPrintedFlag { get; set; }
        public static string StConReftype { get; set; }
        public static string StOrderNumber { get; set; }
        public static string StCopycust { get; set; }
        public static string StRebuildnum { get; set; }
        public static string StPrimary { get; set; }
        public static string StHeaderKey { get; set; }
        public static string StSubLedger { get; set; }
        public static string StAllocCbref { get; set; }
        public static string StCentralised { get; set; }
        public static string StReconciled { get; set; }
        public static string StAllocXref { get; set; }
        public static string StNettBase2 { get; set; }
        public static string StVatBase2 { get; set; }
        public static string StGrossBase2 { get; set; }
        public static string StLDiscBase2 { get; set; }
        public static string StTDiscBase2 { get; set; }
        public static string StBase2Rate { get; set; }
        public static string StTriRate1 { get; set; }
        public static string StBase2Ratechng { get; set; }
        public static string StTriRatechng1 { get; set; }
        public static string StRndDiffBase1 { get; set; }
        public static string StCostvalueBase2 { get; set; }
        public static string StCurrNett { get; set; }
        public static string StCurrTax { get; set; }
        public static string StCurrType { get; set; }
        public static string StTriRate2 { get; set; }
        public static string StTriRatechng2 { get; set; }
        public static string StRndDiffPosted { get; set; }
        public static string StSpclTrantype { get; set; }
        public static string StSrvStatus { get; set; }
        public static string StRndDiffBase2 { get; set; }
        public static string StSource { get; set; }
        public static string StTranOptions { get; set; }
        public static string StReverseVat { get; set; }
        public static string StReverseVatBase2 { get; set; }
        public static string StDebtStatusLink { get; set; }
        public static string StCreditController { get; set; }
        public static string StWriteOffStatus { get; set; }
        public static string StNomCatLink { get; set; }
        public static string StYearLink { get; set; }
        public static string StAllocYearLink { get; set; }
        public static string StWffApprovalStatus { get; set; }
        public static string StDdCollectionStatus { get; set; }
        public static string StQueriedInAcloud { get; set; }
    }
}
