namespace Advanced_Accounting.Classes.MySQLDataConnectors
{
    public static class MySqlSlPlNlDetail
    {
        public static string DetNett { get; set; }
        public static string DetVat { get; set; }
        public static string DetVatcode { get; set; }
        public static string DetGross { get; set; }
        public static string DetUnallocated { get; set; }
        public static string DetBatchFlag { get; set; }
        public static string DetRecurFlag { get; set; }
        public static string DetBatchRef { get; set; }
        public static string DetArchiveFlg { get; set; }
        public static string DetOrigin { get; set; }
        public static string DetLedger { get; set; }
        public static string DetType { get; set; }
        public static string DetDescription { get; set; }
        public static string DetHeaderRef { get; set; }
        public static string DetJnlLineref { get; set; }
        public static string DetPlInternal { get; set; }
        public static string DetDate { get; set; }
        public static string DetTaxSort { get; set; }
        public static string DetCurrTax { get; set; }
        public static string DetTaxWithhld { get; set; }
        public static string DetPlAcqTax { get; set; }
        public static string DetCurrCode { get; set; }
        public static string DetCurrRate { get; set; }
        public static string DetCurrNett { get; set; }
        public static string DetCurrRteflg { get; set; }
        public static string DetCurrUnaloc { get; set; }
        public static string DetCurrLDisc { get; set; }
        public static string DetCurrTDisc { get; set; }
        public static string DetImpexpCode { get; set; }
        public static string DetCountryCde { get; set; }
        public static string DetEcvatType { get; set; }
        public static string DetLDiscount { get; set; }
        public static string DetTDiscount { get; set; }
        public static string DetCostprice { get; set; }
        public static string DetPeriodSort { get; set; }
        public static string DetPeriodnumbr { get; set; }
        public static string DetYear { get; set; }
        public static string DetReconciled { get; set; }
        public static string DetNomPeriod { get; set; }
        public static string DetNomYear { get; set; }
        public static string DetNomPersort { get; set; }
        public static string DetReconRef { get; set; }
        public static string DtReconOrder { get; set; }
        public static string DetUnitPrice { get; set; }
        public static string DetQuantity { get; set; }
        public static string DetUntPriceC { get; set; }
        public static string DetUnitQty { get; set; }
        public static string DetUserPutin { get; set; }
        public static string DetDatePutin { get; set; }
        public static string DetHeaderKey { get; set; }
        public static string DetBatchPostd { get; set; }
        public static string DetSerialno { get; set; }
        public static string DetStksortkey1 { get; set; }
        public static string DetPriceCode { get; set; }
        public static string DetNominaldr { get; set; }
        public static string DetNominalcr { get; set; }
        public static string DetNominalvat { get; set; }
        public static string DetStockCode { get; set; }
        public static string DetAccount { get; set; }
        public static string DetAnalysis { get; set; }
        public static string DetCostheader { get; set; }
        public static string DetCostcentre { get; set; }
        public static string DetAnaltype { get; set; }
        public static string DetPrimary { get; set; }
        public static string DetEcTNature { get; set; }
        public static string DetSubAuditNo { get; set; }
        public static string DetSubLedger { get; set; }
        public static string DetVatRules { get; set; }
        public static string DetVatnondeduct { get; set; }
        public static string DetStksortkey2 { get; set; }
        public static string DetStksortkey3 { get; set; }
        public static string DetStksortkey { get; set; }
        public static string DetLandedCost { get; set; }
        public static string DetDimension1 { get; set; }
        public static string DetDimension2 { get; set; }
        public static string DetDimension3 { get; set; }
        public static string DetChequePayee { get; set; }
        public static string DetNettBase2 { get; set; }
        public static string DetVatBase2 { get; set; }
        public static string DetGrossBase2 { get; set; }
        public static string DetLDiscBase2 { get; set; }
        public static string DetTDiscBase2 { get; set; }
        public static string DetBase2Rate { get; set; }
        public static string DetTriRate1 { get; set; }
        public static string DetBase2Ratechng { get; set; }
        public static string DetTriRatechng1 { get; set; }
        public static string DetCostpriceBase2 { get; set; }
        public static string DetUnitPriceBase2 { get; set; }
        public static string DetTaxWithhldBase2 { get; set; }
        public static string DetPlAcquistnBase2 { get; set; }
        public static string DetCurrGross { get; set; }
        public static string DetTriRate2 { get; set; }
        public static string DetTriRatechng2 { get; set; }
        public static string DetNlcontra { get; set; }
        public static string DetHeaderRef2 { get; set; }
        public static string DetSlplPrimary { get; set; }
        public static string DetSrvStatus { get; set; }
        public static string DetOrderLink { get; set; }
        public static string DetSource { get; set; }
        public static string DetVatReturnPrimary { get; set; }
        public static string DetDeliveryAddress { get; set; }
        public static string DetPostingNo { get; set; }
        public static string DetReverseStatus { get; set; }
        public static string DetMovementLink { get; set; }
        public static string DetNomYearLink { get; set; }
        public static string DetVatRate { get; set; }
    }
}
