namespace Advanced_Accounting.Classes.MySQLDataConnectors
{
    public static class MySqlPlAccounts
    {
        public static string Sucode { get; set; }
        public static string Suname { get; set; }
        public static string Suaddress { get; set; }
        public static string Supostcode { get; set; }
        public static string Suphone { get; set; }
        public static string Suphone2 { get; set; }
        public static string Sufax { get; set; }
        public static string Sucontact { get; set; }
        public static string Susalute { get; set; }
        public static string SuMultiCurr { get; set; }
        public static string SuImportCode { get; set; }
        public static string SuCountryCode { get; set; }
        public static string SuVatRegNo { get; set; }
        public static string SuEcDelivery { get; set; }
        public static string SuEcTNature { get; set; }
        public static string SuEcTMode { get; set; }
        public static string Subalance { get; set; }
        public static string SubalanceC { get; set; }
        public static string Suaged1 { get; set; }
        public static string Suaged2 { get; set; }
        public static string Suaged3 { get; set; }
        public static string Suaged4 { get; set; }
        public static string SuagedUnalloc { get; set; }
        public static string Susort { get; set; }
        public static string Suuser1 { get; set; }
        public static string Suuser2 { get; set; }
        public static string Suuser3 { get; set; }
        public static string Suused { get; set; }
        public static string SuUs1099 { get; set; }
        public static string Suturnoverptd { get; set; }
        public static string SuturnovrL1 { get; set; }
        public static string SuturnovrL2 { get; set; }
        public static string SuturnovrL3 { get; set; }
        public static string SuturnovrL4 { get; set; }
        public static string SuturnovrL5 { get; set; }
        public static string SuturnovrL6 { get; set; }
        public static string SuturnovrL7 { get; set; }
        public static string SuturnovrL8 { get; set; }
        public static string SuturnovrL9 { get; set; }
        public static string SuturnovrL10 { get; set; }
        public static string SuturnovrL11 { get; set; }
        public static string SuturnovrL12 { get; set; }
        public static string SuturnovrL13 { get; set; }
        public static string SuturnovrC1 { get; set; }
        public static string SuturnovrC2 { get; set; }
        public static string SuturnovrC3 { get; set; }
        public static string SuturnovrC4 { get; set; }
        public static string SuturnovrC5 { get; set; }
        public static string SuturnovrC6 { get; set; }
        public static string SuturnovrC7 { get; set; }
        public static string SuturnovrC8 { get; set; }
        public static string SuturnovrC9 { get; set; }
        public static string SuturnovrC10 { get; set; }
        public static string SuturnovrC11 { get; set; }
        public static string SuturnovrC12 { get; set; }
        public static string SuturnovrC13 { get; set; }
        public static string SuturnovrO1 { get; set; }
        public static string SuturnovrO2 { get; set; }
        public static string SuturnovrO3 { get; set; }
        public static string SuturnovrO4 { get; set; }
        public static string SuturnovrO5 { get; set; }
        public static string SuturnovrO6 { get; set; }
        public static string SuturnovrO7 { get; set; }
        public static string SuturnovrO8 { get; set; }
        public static string SuturnovrO9 { get; set; }
        public static string SuturnovrO10 { get; set; }
        public static string SuturnovrO11 { get; set; }
        public static string SuturnovrO12 { get; set; }
        public static string SuturnovrO13 { get; set; }
        public static string Suturnoverytd { get; set; }
        public static string Sucurrencycode { get; set; }
        public static string SuturnovrL1C { get; set; }
        public static string SuturnovrL2C { get; set; }
        public static string SuturnovrL3C { get; set; }
        public static string SuturnovrL4C { get; set; }
        public static string SuturnovrL5C { get; set; }
        public static string SuturnovrL6C { get; set; }
        public static string SuturnovrL7C { get; set; }
        public static string SuturnovrL8C { get; set; }
        public static string SuturnovrL9C { get; set; }
        public static string SuturnovrL10C { get; set; }
        public static string SuturnovrL11C { get; set; }
        public static string SuturnovrL12C { get; set; }
        public static string SuturnovrL13C { get; set; }
        public static string SuturnovrC1C { get; set; }
        public static string SuturnovrC2C { get; set; }
        public static string SuturnovrC3C { get; set; }
        public static string SuturnovrC4C { get; set; }
        public static string SuturnovrC5C { get; set; }
        public static string SuturnovrC6C { get; set; }
        public static string SuturnovrC7C { get; set; }
        public static string SuturnovrC8C { get; set; }
        public static string SuturnovrC9C { get; set; }
        public static string SuturnovrC10C { get; set; }
        public static string SuturnovrC11C { get; set; }
        public static string SuturnovrC12C { get; set; }
        public static string SuturnovrC13C { get; set; }
        public static string SuturnovrO1C { get; set; }
        public static string SuturnovrO2C { get; set; }
        public static string SuturnovrO3C { get; set; }
        public static string SuturnovrO4C { get; set; }
        public static string SuturnovrO5C { get; set; }
        public static string SuturnovrO6C { get; set; }
        public static string SuturnovrO7C { get; set; }
        public static string SuturnovrO8C { get; set; }
        public static string SuturnovrO9C { get; set; }
        public static string SuturnovrO10C { get; set; }
        public static string SuturnovrO11C { get; set; }
        public static string SuturnovrO12C { get; set; }
        public static string SuturnovrO13C { get; set; }
        public static string SuturnovrYtdC { get; set; }
        public static string SuturnovrPtdC { get; set; }
        public static string SuNotes { get; set; }
        public static string SuBankSort { get; set; }
        public static string SuBankAcNo { get; set; }
        public static string SuBankAcName { get; set; }
        public static string SuBankBacsref { get; set; }
        public static string SuBankBankname { get; set; }
        public static string SuRemAddCde { get; set; }
        public static string SuInvAddCde { get; set; }
        public static string SuDelAddCde { get; set; }
        public static string SuStAddCode { get; set; }
        public static string SuDateInv { get; set; }
        public static string SuDatePay { get; set; }
        public static string SuUserPutin { get; set; }
        public static string SuDatePutin { get; set; }
        public static string SuDateEdited { get; set; }
        public static string SuUserEdited { get; set; }
        public static string SuMuStatus { get; set; }
        public static string SuLineDisc { get; set; }
        public static string SuTotDisc { get; set; }
        public static string SuSettDisc1 { get; set; }
        public static string SuSettDisc2 { get; set; }
        public static string SuSettDays1 { get; set; }
        public static string SuSettDays2 { get; set; }
        public static string SuOnStop { get; set; }
        public static string SuCreditLimit { get; set; }
        public static string SuTerms { get; set; }
        public static string SuDelCharge { get; set; }
        public static string SuDelChargeC { get; set; }
        public static string SuMinOrdr { get; set; }
        public static string SuMinOrdrC { get; set; }
        public static string SuDueDays { get; set; }
        public static string SuApDays { get; set; }
        public static string SuDelChgPcnt { get; set; }
        public static string SuDuedateType { get; set; }
        public static string SuPriceKey { get; set; }
        public static string SuAnalysis { get; set; }
        public static string SuTaxCode { get; set; }
        public static string SuBankAnalys { get; set; }
        public static string SuAddressUser1 { get; set; }
        public static string SuAddressUser2 { get; set; }
        public static string SuEmail { get; set; }
        public static string SuPrimary { get; set; }
        public static string SuCurrencyChanged { get; set; }
        public static string SuSource { get; set; }
        public static string SuDocDestination { get; set; }
        public static string SuCountry { get; set; }
        public static string SuDoNotUse { get; set; }
        public static string SuLeadTime { get; set; }
        public static string SuCis { get; set; }
        public static string SuCisTaxStatus { get; set; }
        public static string SuCisUtr { get; set; }
        public static string SuCisInactive { get; set; }
        public static string SuCisBusinessType { get; set; }
        public static string SuCisNiNumber { get; set; }
        public static string SuCisCompanyRegNo { get; set; }
        public static string SuCis300Name { get; set; }
        public static string SuVerificationNumber { get; set; }
        public static string SuDateMatched { get; set; }
        public static string SuPartnershipLink { get; set; }
        public static string SuContractAgreed { get; set; }
        public static string SuCisTitle { get; set; }
        public static string SuCisForename1 { get; set; }
        public static string SuCisForename2 { get; set; }
        public static string SuCisSurname { get; set; }
        public static string SuInsuranceCompany { get; set; }
        public static string SuInsurancePolicyNo { get; set; }
        public static string SuInsuranceExpiryDate { get; set; }
        public static string SuInsuranceChecked { get; set; }
        public static string SuCitbLevy { get; set; }
        public static string SuMatchInProgress { get; set; }
        public static string SuCurrCreditLimit { get; set; }
        public static string SuAntDaysFromDatesOpt { get; set; }
        public static string SuCompanyRegNumber { get; set; }
        public static string SuSwiftCode { get; set; }
        public static string SuMethodOfPayment { get; set; }
    }
}
