namespace Advanced_Accounting.Classes.MySQLDataConnectors
{
    public static class MySqlNlAccounts
    {
        public static string Ncode { get; set; }
        public static string Nname { get; set; }
        public static string Ncurrencycode { get; set; }
        public static string Ntype { get; set; }
        public static string Nopenbalmonth { get; set; }
        public static string Nopenbalyear { get; set; }
        public static string NopenbalmthC { get; set; }
        public static string NopenbalyrC { get; set; }
        public static string Nbalance { get; set; }
        public static string Nturnoverptd { get; set; }
        public static string Nturnoverytd { get; set; }
        public static string Nturnoverly { get; set; }
        public static string NbalanceC { get; set; }
        public static string NturnovrptdC { get; set; }
        public static string NturnovrytdC { get; set; }
        public static string NturnovrlyC { get; set; }
        public static string Nbudgetptd { get; set; }
        public static string Nbudgetytd { get; set; }
        public static string Nbudgetly { get; set; }
        public static string NbudgetptdC { get; set; }
        public static string NbudgetytdC { get; set; }
        public static string NbudgetlyC { get; set; }
        public static string Ncategrycode5 { get; set; }
        public static string Ncategrycode6 { get; set; }
        public static string Ncategrycode7 { get; set; }
        public static string Ncategrycode8 { get; set; }
        public static string Nnotes { get; set; }
        public static string NExcludeTrnrep { get; set; }
        public static string NCountryCode { get; set; }
        public static string NyearEndCode { get; set; }
        public static string Nused { get; set; }
        public static string NProfileRec { get; set; }
        public static string NProfileNl { get; set; }
        public static string NProfileSl { get; set; }
        public static string NProfilePl { get; set; }
        public static string NProfileWarn { get; set; }
        public static string NReconCounter { get; set; }
        public static string Nreconbalance { get; set; }
        public static string NreconbalanceC { get; set; }
        public static string NIncome { get; set; }
        public static string NIncomeC { get; set; }
        public static string NExpenses { get; set; }
        public static string NExpensesC { get; set; }
        public static string Nopenbalancely { get; set; }
        public static string NopenbalanclyC { get; set; }
        public static string NturnoverL1 { get; set; }
        public static string NturnoverL2 { get; set; }
        public static string NturnoverL3 { get; set; }
        public static string NturnoverL4 { get; set; }
        public static string NturnoverL5 { get; set; }
        public static string NturnoverL6 { get; set; }
        public static string NturnoverL7 { get; set; }
        public static string NturnoverL8 { get; set; }
        public static string NturnoverL9 { get; set; }
        public static string NturnoverL10 { get; set; }
        public static string NturnoverL11 { get; set; }
        public static string NturnoverL12 { get; set; }
        public static string NturnoverL13 { get; set; }
        public static string NturnoverC1 { get; set; }
        public static string NturnoverC2 { get; set; }
        public static string NturnoverC3 { get; set; }
        public static string NturnoverC4 { get; set; }
        public static string NturnoverC5 { get; set; }
        public static string NturnoverC6 { get; set; }
        public static string NturnoverC7 { get; set; }
        public static string NturnoverC8 { get; set; }
        public static string NturnoverC9 { get; set; }
        public static string NturnoverC10 { get; set; }
        public static string NturnoverC11 { get; set; }
        public static string NturnoverC12 { get; set; }
        public static string NturnoverC13 { get; set; }
        public static string NturnoverN1 { get; set; }
        public static string NturnoverN2 { get; set; }
        public static string NturnoverN3 { get; set; }
        public static string NturnoverN4 { get; set; }
        public static string NturnoverN5 { get; set; }
        public static string NturnoverN6 { get; set; }
        public static string NturnoverN7 { get; set; }
        public static string NturnoverN8 { get; set; }
        public static string NturnoverN9 { get; set; }
        public static string NturnoverN10 { get; set; }
        public static string NturnoverN11 { get; set; }
        public static string NturnoverN12 { get; set; }
        public static string NturnoverN13 { get; set; }
        public static string NturnoverL1C { get; set; }
        public static string NturnoverL2C { get; set; }
        public static string NturnoverL3C { get; set; }
        public static string NturnoverL4C { get; set; }
        public static string NturnoverL5C { get; set; }
        public static string NturnoverL6C { get; set; }
        public static string NturnoverL7C { get; set; }
        public static string NturnoverL8C { get; set; }
        public static string NturnoverL9C { get; set; }
        public static string NturnoverL10C { get; set; }
        public static string NturnoverL11C { get; set; }
        public static string NturnoverL12C { get; set; }
        public static string NturnoverL13C { get; set; }
        public static string NturnoverC1C { get; set; }
        public static string NturnoverC2C { get; set; }
        public static string NturnoverC3C { get; set; }
        public static string NturnoverC4C { get; set; }
        public static string NturnoverC5C { get; set; }
        public static string NturnoverC6C { get; set; }
        public static string NturnoverC7C { get; set; }
        public static string NturnoverC8C { get; set; }
        public static string NturnoverC9C { get; set; }
        public static string NturnoverC10C { get; set; }
        public static string NturnoverC11C { get; set; }
        public static string NturnoverC12C { get; set; }
        public static string NturnoverC13C { get; set; }
        public static string NturnoverN1C { get; set; }
        public static string NturnoverN2C { get; set; }
        public static string NturnoverN3C { get; set; }
        public static string NturnoverN4C { get; set; }
        public static string NturnoverN5C { get; set; }
        public static string NturnoverN6C { get; set; }
        public static string NturnoverN7C { get; set; }
        public static string NturnoverN8C { get; set; }
        public static string NturnoverN9C { get; set; }
        public static string NturnoverN10C { get; set; }
        public static string NturnoverN11C { get; set; }
        public static string NturnoverN12C { get; set; }
        public static string NturnoverN13C { get; set; }
        public static string NbudgetL1 { get; set; }
        public static string NbudgetL2 { get; set; }
        public static string NbudgetL3 { get; set; }
        public static string NbudgetL4 { get; set; }
        public static string NbudgetL5 { get; set; }
        public static string NbudgetL6 { get; set; }
        public static string NbudgetL7 { get; set; }
        public static string NbudgetL8 { get; set; }
        public static string NbudgetL9 { get; set; }
        public static string NbudgetL10 { get; set; }
        public static string NbudgetL11 { get; set; }
        public static string NbudgetL12 { get; set; }
        public static string NbudgetL13 { get; set; }
        public static string NbudgetC1 { get; set; }
        public static string NbudgetC2 { get; set; }
        public static string NbudgetC3 { get; set; }
        public static string NbudgetC4 { get; set; }
        public static string NbudgetC5 { get; set; }
        public static string NbudgetC6 { get; set; }
        public static string NbudgetC7 { get; set; }
        public static string NbudgetC8 { get; set; }
        public static string NbudgetC9 { get; set; }
        public static string NbudgetC10 { get; set; }
        public static string NbudgetC11 { get; set; }
        public static string NbudgetC12 { get; set; }
        public static string NbudgetC13 { get; set; }
        public static string NbudgetN1 { get; set; }
        public static string NbudgetN2 { get; set; }
        public static string NbudgetN3 { get; set; }
        public static string NbudgetN4 { get; set; }
        public static string NbudgetN5 { get; set; }
        public static string NbudgetN6 { get; set; }
        public static string NbudgetN7 { get; set; }
        public static string NbudgetN8 { get; set; }
        public static string NbudgetN9 { get; set; }
        public static string NbudgetN10 { get; set; }
        public static string NbudgetN11 { get; set; }
        public static string NbudgetN12 { get; set; }
        public static string NbudgetN13 { get; set; }
        public static string NbudgetL1O { get; set; }
        public static string NbudgetL2O { get; set; }
        public static string NbudgetL3O { get; set; }
        public static string NbudgetL4O { get; set; }
        public static string NbudgetL5O { get; set; }
        public static string NbudgetL6O { get; set; }
        public static string NbudgetL7O { get; set; }
        public static string NbudgetL8O { get; set; }
        public static string NbudgetL9O { get; set; }
        public static string NbudgetL10O { get; set; }
        public static string NbudgetL11O { get; set; }
        public static string NbudgetL12O { get; set; }
        public static string NbudgetL13O { get; set; }
        public static string NbudgetC1O { get; set; }
        public static string NbudgetC2O { get; set; }
        public static string NbudgetC3O { get; set; }
        public static string NbudgetC4O { get; set; }
        public static string NbudgetC5O { get; set; }
        public static string NbudgetC6O { get; set; }
        public static string NbudgetC7O { get; set; }
        public static string NbudgetC8O { get; set; }
        public static string NbudgetC9O { get; set; }
        public static string NbudgetC10O { get; set; }
        public static string NbudgetC11O { get; set; }
        public static string NbudgetC12O { get; set; }
        public static string NbudgetC13O { get; set; }
        public static string NbudgetN1O { get; set; }
        public static string NbudgetN2O { get; set; }
        public static string NbudgetN3O { get; set; }
        public static string NbudgetN4O { get; set; }
        public static string NbudgetN5O { get; set; }
        public static string NbudgetN6O { get; set; }
        public static string NbudgetN7O { get; set; }
        public static string NbudgetN8O { get; set; }
        public static string NbudgetN9O { get; set; }
        public static string NbudgetN10O { get; set; }
        public static string NbudgetN11O { get; set; }
        public static string NbudgetN12O { get; set; }
        public static string NbudgetN13O { get; set; }
        public static string NUserEdited { get; set; }
        public static string NUserPutin { get; set; }
        public static string NDatePutin { get; set; }
        public static string NDateEdited { get; set; }
        public static string NMuStatus { get; set; }
        public static string Ncategrycode4 { get; set; }
        public static string NcopyAcccode { get; set; }
        public static string Ncategrycode1 { get; set; }
        public static string Ncategrycodee2 { get; set; }
        public static string Ncategrycode3 { get; set; }
        public static string Nmajorheadcode { get; set; }
        public static string NPrimary { get; set; }
        public static string NLastStatement { get; set; }
        public static string NExcludeRecrep { get; set; }
        public static string NCentralised { get; set; }
        public static string NVatnondeduct { get; set; }
        public static string NVatcode { get; set; }
        public static string NForceCosting { get; set; }
        public static string NSource { get; set; }
        public static string NUseZeroBudget { get; set; }
        public static string NOverdraft { get; set; }
        public static string NDoNotUse { get; set; }
        public static string NEmissionsGroupLink { get; set; }
        public static string NClassificationLink { get; set; }
        public static string NAccountForCo2 { get; set; }
        public static string NDefaultCostcentre { get; set; }
        public static string NreportingCode { get; set; }
    }
}
