namespace Advanced_Accounting.Classes.MySQLDataConnectors
{
    public static class MySqlSlAddresses
    {
        public static string AdAccCode { get; set; }
        public static string AdCode { get; set; }
        public static string AdConCode { get; set; }
        public static string AdAddress { get; set; }
        public static string AdPostcode { get; set; }
        public static string AdHomePhone { get; set; }
        public static string AdExtension { get; set; }
        public static string AdPhone { get; set; }
        public static string AdFax { get; set; }
        public static string AdMobile { get; set; }
        public static string AdEMail { get; set; }
        public static string AdContact { get; set; }
        public static string AdContSalute { get; set; }
        public static string AdInvAddress { get; set; }
        public static string AdDelAddress { get; set; }
        public static string AdStatAddress { get; set; }
        public static string AdProspect { get; set; }
        public static string AdAccountname { get; set; }
        public static string AdNote { get; set; }
        public static string AdConTitle { get; set; }
        public static string AdConInitials { get; set; }
        public static string AdConSurname { get; set; }
        public static string AdConJob { get; set; }
        public static string AdConFname { get; set; }
        public static string AdDealercode { get; set; }
        public static string AdUsertext1 { get; set; }
        public static string AdUsertext2 { get; set; }
        public static string AdUserdate1 { get; set; }
        public static string AdUsernum1 { get; set; }
        public static string AdUserflag1 { get; set; }
        public static string AdUserflag2 { get; set; }
        public static string AdUserflag3 { get; set; }
        public static string AdUserflag4 { get; set; }
        public static string AdEditedTime { get; set; }
        public static string AdRecallTime { get; set; }
        public static string AdUserEdited { get; set; }
        public static string AdUserPutin { get; set; }
        public static string AdDatePutin { get; set; }
        public static string AdDateEdited { get; set; }
        public static string SlAdPrimary { get; set; }
        public static string AdUsertext3 { get; set; }
        public static string AdUsertext4 { get; set; }
        public static string AdUsertext5 { get; set; }
        public static string AdUsertext6 { get; set; }
        public static string AdUserdate2 { get; set; }
        public static string AdUserdate3 { get; set; }
        public static string AdUsernum2 { get; set; }
        public static string AdUsernum3 { get; set; }
        public static string AdUsertext7 { get; set; }
        public static string AdUsertext8 { get; set; }
        public static string AdUsertext9 { get; set; }
        public static string AdUsertext10 { get; set; }
        public static string AdAddressUser1 { get; set; }
        public static string AdAddressUser2 { get; set; }
        public static string AdUserAloc { get; set; }
        public static string AdAnalysis { get; set; }
        public static string AdLevel { get; set; }
        public static string AdGroup { get; set; }
        public static string AdDelAddress2 { get; set; }
        public static string AdDlrNotification { get; set; }
        public static string AdDlrNotificationDate { get; set; }
        public static string AdCntNotification { get; set; }
        public static string AdCntNotificationDate { get; set; }
        public static string AdSource { get; set; }
        public static string AdCcEmail { get; set; }
        public static string AdCountry { get; set; }
        public static string AdDoNotUse { get; set; }
        public static string AdCountryCode { get; set; }
        public static string AdExportCode { get; set; }
        public static string AdBranchId { get; set; }
        public static string AdVatRegNo { get; set; }
        public static string AdEcDelivery { get; set; }
        public static string AdEcTNature { get; set; }
        public static string AdEcTMode { get; set; }
        public static string AdUsedFlag { get; set; }
        public static string AdDoNotEmail { get; set; }
        public static string AdDateAllocated { get; set; }
        public static string AdDeliveryRoute { get; set; }
    }
}
